"use strict";(()=>{var ot=(t,n)=>()=>(t&&(n=t(t=0)),n);var I=(t,n)=>()=>(n||t((n={exports:{}}).exports,n),n.exports);var L=(t,n,s)=>new Promise((r,l)=>{var c=p=>{try{h(s.next(p))}catch(v){l(v)}},a=p=>{try{h(s.throw(p))}catch(v){l(v)}},h=p=>p.done?r(p.value):Promise.resolve(p.value).then(c,a);h((s=s.apply(t,n)).next())});var et,tt=ot(()=>{et="2.1.0"});var nt=I((X,D)=>{(function(t,n){typeof X=="object"&&typeof D!="undefined"?D.exports=n():typeof define=="function"&&define.amd?define(n):(t=typeof globalThis!="undefined"?globalThis:t||self).dayjs=n()})(X,function(){"use strict";var t=1e3,n=6e4,s=36e5,r="millisecond",l="second",c="minute",a="hour",h="day",p="week",v="month",k="quarter",C="year",A="date",M="Invalid Date",m=/^(\d{4})[-/]?(\d{1,2})?[-/]?(\d{0,2})[Tt\s]*(\d{1,2})?:?(\d{1,2})?:?(\d{1,2})?[.:]?(\d+)?$/,H=/\[([^\]]+)]|Y{1,4}|M{1,4}|D{1,2}|d{1,4}|H{1,2}|h{1,2}|a|A|m{1,2}|s{1,2}|Z{1,2}|SSS/g,o={name:"en",weekdays:"Sunday_Monday_Tuesday_Wednesday_Thursday_Friday_Saturday".split("_"),months:"January_February_March_April_May_June_July_August_September_October_November_December".split("_"),ordinal:function(y){var g=["th","st","nd","rd"],d=y%100;return"["+y+(g[(d-20)%10]||g[d]||g[0])+"]"}},i=function(y,g,d){var f=String(y);return!f||f.length>=g?y:""+Array(g+1-f.length).join(d)+y},O={s:i,z:function(y){var g=-y.utcOffset(),d=Math.abs(g),f=Math.floor(d/60),u=d%60;return(g<=0?"+":"-")+i(f,2,"0")+":"+i(u,2,"0")},m:function y(g,d){if(g.date()<d.date())return-y(d,g);var f=12*(d.year()-g.year())+(d.month()-g.month()),u=g.clone().add(f,v),T=d-u<0,S=g.clone().add(f+(T?-1:1),v);return+(-(f+(d-u)/(T?u-S:S-u))||0)},a:function(y){return y<0?Math.ceil(y)||0:Math.floor(y)},p:function(y){return{M:v,y:C,w:p,d:h,D:A,h:a,m:c,s:l,ms:r,Q:k}[y]||String(y||"").toLowerCase().replace(/s$/,"")},u:function(y){return y===void 0}},j="en",x={};x[j]=o;var w="$isDayjsObject",V=function(y){return y instanceof P||!(!y||!y[w])},e=function y(g,d,f){var u;if(!g)return j;if(typeof g=="string"){var T=g.toLowerCase();x[T]&&(u=T),d&&(x[T]=d,u=T);var S=g.split("-");if(!u&&S.length>1)return y(S[0])}else{var B=g.name;x[B]=g,u=B}return!f&&u&&(j=u),u||!f&&j},_=function(y,g){if(V(y))return y.clone();var d=typeof g=="object"?g:{};return d.date=y,d.args=arguments,new P(d)},b=O;b.l=e,b.i=V,b.w=function(y,g){return _(y,{locale:g.$L,utc:g.$u,x:g.$x,$offset:g.$offset})};var P=function(){function y(d){this.$L=e(d.locale,null,!0),this.parse(d),this.$x=this.$x||d.x||{},this[w]=!0}var g=y.prototype;return g.parse=function(d){this.$d=function(f){var u=f.date,T=f.utc;if(u===null)return new Date(NaN);if(b.u(u))return new Date;if(u instanceof Date)return new Date(u);if(typeof u=="string"&&!/Z$/i.test(u)){var S=u.match(m);if(S){var B=S[2]-1||0,W=(S[7]||"0").substring(0,3);return T?new Date(Date.UTC(S[1],B,S[3]||1,S[4]||0,S[5]||0,S[6]||0,W)):new Date(S[1],B,S[3]||1,S[4]||0,S[5]||0,S[6]||0,W)}}return new Date(u)}(d),this.init()},g.init=function(){var d=this.$d;this.$y=d.getFullYear(),this.$M=d.getMonth(),this.$D=d.getDate(),this.$W=d.getDay(),this.$H=d.getHours(),this.$m=d.getMinutes(),this.$s=d.getSeconds(),this.$ms=d.getMilliseconds()},g.$utils=function(){return b},g.isValid=function(){return this.$d.toString()!==M},g.isSame=function(d,f){var u=_(d);return this.startOf(f)<=u&&u<=this.endOf(f)},g.isAfter=function(d,f){return _(d)<this.startOf(f)},g.isBefore=function(d,f){return this.endOf(f)<_(d)},g.$g=function(d,f,u){return b.u(d)?this[f]:this.set(u,d)},g.unix=function(){return Math.floor(this.valueOf()/1e3)},g.valueOf=function(){return this.$d.getTime()},g.startOf=function(d,f){var u=this,T=!!b.u(f)||f,S=b.p(d),B=function(E,N){var q=b.w(u.$u?Date.UTC(u.$y,N,E):new Date(u.$y,N,E),u);return T?q:q.endOf(h)},W=function(E,N){return b.w(u.toDate()[E].apply(u.toDate("s"),(T?[0,0,0,0]:[23,59,59,999]).slice(N)),u)},F=this.$W,z=this.$M,Z=this.$D,J="set"+(this.$u?"UTC":"");switch(S){case C:return T?B(1,0):B(31,11);case v:return T?B(1,z):B(0,z+1);case p:var Y=this.$locale().weekStart||0,G=(F<Y?F+7:F)-Y;return B(T?Z-G:Z+(6-G),z);case h:case A:return W(J+"Hours",0);case a:return W(J+"Minutes",1);case c:return W(J+"Seconds",2);case l:return W(J+"Milliseconds",3);default:return this.clone()}},g.endOf=function(d){return this.startOf(d,!1)},g.$set=function(d,f){var u,T=b.p(d),S="set"+(this.$u?"UTC":""),B=(u={},u[h]=S+"Date",u[A]=S+"Date",u[v]=S+"Month",u[C]=S+"FullYear",u[a]=S+"Hours",u[c]=S+"Minutes",u[l]=S+"Seconds",u[r]=S+"Milliseconds",u)[T],W=T===h?this.$D+(f-this.$W):f;if(T===v||T===C){var F=this.clone().set(A,1);F.$d[B](W),F.init(),this.$d=F.set(A,Math.min(this.$D,F.daysInMonth())).$d}else B&&this.$d[B](W);return this.init(),this},g.set=function(d,f){return this.clone().$set(d,f)},g.get=function(d){return this[b.p(d)]()},g.add=function(d,f){var u,T=this;d=Number(d);var S=b.p(f),B=function(z){var Z=_(T);return b.w(Z.date(Z.date()+Math.round(z*d)),T)};if(S===v)return this.set(v,this.$M+d);if(S===C)return this.set(C,this.$y+d);if(S===h)return B(1);if(S===p)return B(7);var W=(u={},u[c]=n,u[a]=s,u[l]=t,u)[S]||1,F=this.$d.getTime()+d*W;return b.w(F,this)},g.subtract=function(d,f){return this.add(-1*d,f)},g.format=function(d){var f=this,u=this.$locale();if(!this.isValid())return u.invalidDate||M;var T=d||"YYYY-MM-DDTHH:mm:ssZ",S=b.z(this),B=this.$H,W=this.$m,F=this.$M,z=u.weekdays,Z=u.months,J=u.meridiem,Y=function(N,q,U,Q){return N&&(N[q]||N(f,T))||U[q].slice(0,Q)},G=function(N){return b.s(B%12||12,N,"0")},E=J||function(N,q,U){var Q=N<12?"AM":"PM";return U?Q.toLowerCase():Q};return T.replace(H,function(N,q){return q||function(U){switch(U){case"YY":return String(f.$y).slice(-2);case"YYYY":return b.s(f.$y,4,"0");case"M":return F+1;case"MM":return b.s(F+1,2,"0");case"MMM":return Y(u.monthsShort,F,Z,3);case"MMMM":return Y(Z,F);case"D":return f.$D;case"DD":return b.s(f.$D,2,"0");case"d":return String(f.$W);case"dd":return Y(u.weekdaysMin,f.$W,z,2);case"ddd":return Y(u.weekdaysShort,f.$W,z,3);case"dddd":return z[f.$W];case"H":return String(B);case"HH":return b.s(B,2,"0");case"h":return G(1);case"hh":return G(2);case"a":return E(B,W,!0);case"A":return E(B,W,!1);case"m":return String(W);case"mm":return b.s(W,2,"0");case"s":return String(f.$s);case"ss":return b.s(f.$s,2,"0");case"SSS":return b.s(f.$ms,3,"0");case"Z":return S}return null}(N)||S.replace(":","")})},g.utcOffset=function(){return 15*-Math.round(this.$d.getTimezoneOffset()/15)},g.diff=function(d,f,u){var T,S=this,B=b.p(f),W=_(d),F=(W.utcOffset()-this.utcOffset())*n,z=this-W,Z=function(){return b.m(S,W)};switch(B){case C:T=Z()/12;break;case v:T=Z();break;case k:T=Z()/3;break;case p:T=(z-F)/6048e5;break;case h:T=(z-F)/864e5;break;case a:T=z/s;break;case c:T=z/n;break;case l:T=z/t;break;default:T=z}return u?T:b.a(T)},g.daysInMonth=function(){return this.endOf(v).$D},g.$locale=function(){return x[this.$L]},g.locale=function(d,f){if(!d)return this.$L;var u=this.clone(),T=e(d,f,!0);return T&&(u.$L=T),u},g.clone=function(){return b.w(this.$d,this)},g.toDate=function(){return new Date(this.valueOf())},g.toJSON=function(){return this.isValid()?this.toISOString():null},g.toISOString=function(){return this.$d.toISOString()},g.toString=function(){return this.$d.toUTCString()},y}(),R=P.prototype;return _.prototype=R,[["$ms",r],["$s",l],["$m",c],["$H",a],["$W",h],["$M",v],["$y",C],["$D",A]].forEach(function(y){R[y[1]]=function(g){return this.$g(g,y[0],y[1])}}),_.extend=function(y,g){return y.$i||(y(g,P,_),y.$i=!0),_},_.locale=e,_.isDayjs=V,_.unix=function(y){return _(1e3*y)},_.en=x[j],_.Ls=x,_.p={},_})});var rt=I(st=>{tt();var K=nt();fetch("widgets/tvprogram/i18n/translations.json").then(t=>L(st,null,function*(){let n=yield t.json();$.extend(!0,systemDictionary,n)}));$.extend(!0,systemDictionary,{});vis.binds.tvprogram={version:et,showVersion:function(){vis.binds.tvprogram.version&&(console.log(`Version tvprogram: ${vis.binds.tvprogram.version}`),vis.binds.tvprogram.version=null)},pending:{},categories:null,channels:null,genres:null,tvprogram:[],infos:null,requests:[],search:{visTvprogram:null,bound:{},searchdata:[],searchresult:[],createWidget:function(t,n,s,r){return L(this,null,function*(){let l=$(`#${t}`);if(!l.length)return setTimeout(function(){vis.binds.tvprogram.search.createWidget(t,n,s,r)},100);if(console.log("createWidget start"),this.visTvprogram=vis.binds.tvprogram,!s.tvprogram_oid||s.tvprogram_oid=="")return;let[c,a]=this.visTvprogram.getInstanceInfo(s.tvprogram_oid);if(!a&&!c)return;let h=this.visTvprogram.realBackgroundColor($(`#${t}`)[0]);this.visTvprogram.checkStyle("background-color",$(`#${t}`)[0].style.cssText)==""&&$(`#${t}`).css("background-color",h);let p=parseInt(s.tvprogram_maxresults)||10,v=parseInt(s.tvprogram_heightRow)||35,k=parseInt(s.tvprogram_broadcastfontpercent)||75,C=s.tvprogram_highlightcolor||"yellow",A=s.tvprogram_showpictures||!1,M=s.tvprogram_dialogwidthpercent/100||.9,m=s.tvprogram_dialogheightpercent/100||.9;if(this.searchresult[a]||(this.searchresult[a]={}),this.searchresult[a][t]||(this.searchresult[a][t]=[]),this.searchdata[a]||(this.searchdata[a]={}),this.searchdata[a][t]||(this.searchdata[a][t]={datefrom:new Date().toISOString().split("T")[0],categoryfilter:"",textfilter:"",maxresults:p||10}),this.bound[a]||(this.bound[a]={}),this.bound[a][t]||(this.bound[a][t]=!1),a&&!this.bound[a][t]&&(vis.editMode||(this.bound[a][t]=!0,vis.binds.tvprogram.bindStates(l,[`${a}.config`,`${a}.favorites`,`${a}.channelfilter`],this.onChange.bind(this,t,n,s,r,a)))),this.visTvprogram.infos||(this.visTvprogram.infos=yield this.visTvprogram.loadServerInfosAsync(c)),this.visTvprogram.categories||(this.visTvprogram.categories=yield this.visTvprogram.loadCategories(c,t)),this.visTvprogram.channels||(this.visTvprogram.channels=yield this.visTvprogram.loadChannels(c,t)),this.visTvprogram.infos==null||!Object.prototype.hasOwnProperty.call(this.visTvprogram.infos,"tvprogram")||this.visTvprogram.categories.length==0||this.visTvprogram.channels.length==0)return;let H=this.visTvprogram.categories.map(x=>`<option value="${x.id}" ${this.searchdata[a][t].categoryfilter==x.id?" selected":""}>${x.title}</option>`);H=`<option value="" ${this.searchdata[a][t].categoryfilter==""?" selected":""}></option>${H}`,$(`#${t}broadcastdlg`).data({dialogwidthpercent:M,dialogheightpercent:m});let o="";o+=`<style> 
`,o+=`#${t} * {
`,o+=`   box-sizing: border-box; 
`,o+=`} 
`,o+=`#${t} .tv-search {
`,o+=`   width: 100%; 
`,o+=`   height: 100%; 
`,o+=`   white-space:nowrap; 
`,o+=`   display:flex; 
`,o+=`   flex-direction: column; 
`,o+=`} 
`,o+=`#${t} .tv-form {
`,o+=`   padding: 5px 0px; 
`,o+=`} 
`,o+=`#${t} .tv-result {
`,o+=`   overflow: hidden; 
`,o+=`   overflow-y: auto; 
`,o+=`} 
`,o+=`#${t} .tv-row {
`,o+=`   margin: 0px; 
`,o+=`   padding: 0px; 
`,o+=`   width: 100%; 
`,o+=`} 
`,o+=`#${t} .tv-search .tv-row:nth-child(odd) {
`,o+=`   background-color: rgba(128,127,127,.65); 
`,o+=`   padding: 0px; 
`,o+=`} 
`,o+=`#${t} .tv-search .tv-row:nth-child(even) {
`,o+=`   background-color: rgba(128,127,127,.55); 
`,o+=`   padding: 0px; 
`,o+=`} 
`,o+=`#${t} .tv-item {
`,o+=`   display: inline-block; 
`,o+=`   vertical-align: middle; 
`,o+=`   border: solid #80808033; 
`,o+=`   border-width:1px 0px 0px 1px; 
`,o+=`} 
`,o+=`#${t} .channel {
`,o+=`   width: ${v}px; 
`,o+=`   height: ${v}px; 
`,o+=`   padding: 1px; 
`,o+=`   background-color: ${h}; 
`,o+=`} 
`,o+=`#${t} .broadcast {
`,o+=`   height: ${v}px; 
`,o+=`   padding: 3px; 
`,o+=`   font-size: ${k}%; 
`,o+=`   overflow: hidden; 
`,o+=`   width: 100%; 
`,o+=`} 
`,o+=`#${t} .broadcastelement {
`,o+=`   width: 100%; 
`,o+=`   height: 100%; 
`,o+=`   display: table-cell; 
`,o+=`} 
`,o+=`#${t} .broadcastelement .star  {
`,o+=`   display: inline-block; 
`,o+=`   margin: 0px 2px; 
`,o+=`} 
`,o+=`#${t} .broadcastelement .star svg {
`,o+=`   height: 1em; 
`,o+=`   width: 1em; 
`,o+=`   position: relative; 
`,o+=`   top: .125em; 
`,o+=`} 
`,o+=`#${t} .broadcastelement.selected .star svg path {
`,o+=`   color: ${C}; 
`,o+=`} 
`,o+=`#${t} .broadcastelement.selected {
`,o+=`   color: ${C}; 
`,o+=`} 
`,o+=`#${t} .broadcastimage {
`,o+=`   height: ${v-7}px; 
`,o+=`   padding-right: 3px; 
`,o+=`   float: left; 
`,o+=`} 
`,o+=`.${t}.no-titlebar .ui-dialog-titlebar {
`,o+=`   display:none; 
`,o+=`} 
`,o+=`#${t}broadcastdlg  {
`,o+=`   z-index:12; 
`,o+=`} 
`,o+=`#${t}broadcastdlg .event-container.tv-dlg-row {
`,o+=`   height:100%; 
`,o+=`   display:flex; 
`,o+=`   flex-direction:row; 
`,o+=`   overflow:hidden; 
`,o+=`} 
`,o+=`#${t}broadcastdlg .event-container.tv-dlg-col {
`,o+=`   height:100%; 
`,o+=`   display:flex; 
`,o+=`   flex-direction:column; 
`,o+=`   overflow:hidden; 
`,o+=`   font-size:75%; 
`,o+=`} 
`,o+=`#${t}broadcastdlg .event-picture.tv-dlg-row {
`,o+=`   width:50%; 
`,o+=`} 
`,o+=`#${t}broadcastdlg .event-picture.tv-dlg-col {
`,o+=`   height:30%; 
`,o+=`} 
`,o+=`#${t}broadcastdlg .event-data {
`,o+=`   overflow-y:auto; 
`,o+=`} 
`,o+=`#${t}broadcastdlg .event-picture img {
`,o+=`   width:auto; 
`,o+=`   height:auto; 
`,o+=`   max-width:100%; 
`,o+=`   max-height:100%; 
`,o+=`   display:block; 
`,o+=`   margin:auto; 
`,o+=`} 
`,o+=`#${t}broadcastdlg .event-picture img {
`,o+=`   width:auto; 
`,o+=`   height:auto; 
`,o+=`   max-width:100%; 
`,o+=`   max-height:100%; 
`,o+=`   display:block; 
`,o+=`   margin:auto; 
`,o+=`} 
`,o+=`#${t}broadcastdlg .dialogcolumn.tv-dlg-row {
`,o+=`   flex:1; 
`,o+=`   padding:5px; 
`,o+=`} 
`,o+=`#${t}broadcastdlg .dialogcolumn.tv-dlg-col {
`,o+=`   padding:5px; 
`,o+=`} 
`,o+=`#${t}broadcastdlg .button {
`,o+=`   display:inline-block; 
`,o+=`   width: 35px; 
`,o+=`   height: 35px; 
`,o+=`   vertical-align: middle; 
`,o+=`   position: relative; 
`,o+=`   float: right; 
`,o+=`} 
`,o+=`#${t}broadcastdlg .star.selected svg  {
`,o+=`   filter: drop-shadow( 2px 2px 2px rgba(0, 0, 0, .7))
`,o+=`} 
`,o+=`#${t} .broadcastelement.selected .star svg path, #${t}broadcastdlg .star.selected {
`,o+=`   color: ${C}; 
`,o+=`} 
`,o+=`</style> 
`,o+='  <div class="svgcontainer">',o+='<svg style="display:none;"><symbol id="star-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" /></symbol></svg>',o+='<svg style="display:none;"><symbol id="copy-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M19,21H8V7H19M19,5H8A2,2 0 0,0 6,7V21A2,2 0 0,0 8,23H19A2,2 0 0,0 21,21V7A2,2 0 0,0 19,5M16,1H4A2,2 0 0,0 2,3V17H4V3H16V1Z" /></symbol></svg>',o+='<svg style="display:none;"><symbol id="switch-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M21,3H3C1.89,3 1,3.89 1,5V17A2,2 0 0,0 3,19H8V21H16V19H21A2,2 0 0,0 23,17V5C23,3.89 22.1,3 21,3M21,17H3V5H21M16,11L9,15V7" /></symbol></svg>',o+='<svg style="display:none;"><symbol id="record-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12.5,5A7.5,7.5 0 0,0 5,12.5A7.5,7.5 0 0,0 12.5,20A7.5,7.5 0 0,0 20,12.5A7.5,7.5 0 0,0 12.5,5M7,10H9A1,1 0 0,1 10,11V12C10,12.5 9.62,12.9 9.14,12.97L10.31,15H9.15L8,13V15H7M12,10H14V11H12V12H14V13H12V14H14V15H12A1,1 0 0,1 11,14V11A1,1 0 0,1 12,10M16,10H18V11H16V14H18V15H16A1,1 0 0,1 15,14V11A1,1 0 0,1 16,10M8,11V12H9V11" /></symbol></svg>',o+="  </div>",o+=`  <form data-instance="${c}" data-dp="${a}" data-widgetid="${t}" data-maxresults="${p}" >`,o+='    <label for="tvsearch">Search:',o+=`      <input name="tvsearch" type="text" id="tvsearch" value="${this.searchdata[a][t].textfilter}" placeholder="Search">`,o+="    </label>",o+='    <label for="tvfrom">From:',o+=`      <input name="tvfrom" autocomplete="off"  type="date" id="tvfrom" min="${this.visTvprogram.infos.tvprogram[0]}" max="${this.visTvprogram.infos.tvprogram[this.visTvprogram.infos.tvprogram.length-1]}" value="${this.searchdata[a][t].datefrom}">`,o+="    </label>",o+='    <label for="tvcategory">Category:',o+='      <select name="tvcategory" id="tvcategory" >',o+=H,o+="      </select>",o+="    </label>",o+="  <button>Search</Search>",o+="  </form>",$(`#${t} .tv-form`).html(o),$(`#${t} .tv-form form`).submit(this.onSubmitSearch.bind(this,t,n,s,r));let i,O;o="";let j=this.visTvprogram.getConfigFavorites(a);this.searchresult[a][t].map((x,w)=>{if(w+1>p)return;let V=this.visTvprogram.channels.find(b=>b.id==x.channel);i=j.indexOf(x.title)>-1,O=x.airDate,o+='    <ul class="tv-row">',o+='       <li class="tv-item channel">',o+=`          <img width="100%" height="100%" data-channelid="${V.channelId}" data-dp="${a}" data-instance="${c}" src="https://tvfueralle.de/channel-logos/${V.channelId}.png" alt="" class="channel-logo"  onclick="vis.binds.tvprogram.onclickChannelSwitch(this,event)">`,o+="       </li>",o+='       <li class="tv-item broadcast">',o+=`             <div class="broadcastelement ${i?"selected":""}" data-widgetid="${t}" data-eventid="${x.id}" data-viewdate="${O}" data-instance="${c}" data-dp="${a}" data-view="" >`,x.photo.url&&A&&(o+=`<div><img class="broadcastimage" src="https://tvfueralle.de${x.photo.url}"></div>`),o+='                 <div class="broadcasttitle">',o+=`                     ${x.title}`,o+=`                     <div class="star" data-viewdate="${O}" data-eventid="${x.id}" data-instance="${c}" data-dp="${a}" onclick="return vis.binds.tvprogram.onclickFavorite(this,event)"><svg width="100%" height="100%" ><use xlink:href="#star-icon"></use></svg></div>`,o+="                 </div>";let e=new Date(x.startTime),_=new Date(x.endTime);o+='                 <div class="broadcasttime">',o+=`${`0${e.getDate()}`.slice(-2)}.${`0${parseInt(e.getMonth()+1)}`.slice(-2)}.${`0${e.getFullYear()}`.slice(-4)} `,o+=`${`0${e.getHours()}`.slice(-2)}:${`0${e.getMinutes()}`.slice(-2)}`,o+=" - ",o+=`${`0${_.getHours()}`.slice(-2)}:${`0${_.getMinutes()}`.slice(-2)}`,o+="                 </div>",o+="             </div>",o+="       </li>",o+="    </ul>"}),$(`#${t} .tv-result`).html(o),$(`#${t} .tv-result .broadcastelement`).click(vis.binds.tvprogram.onclickBroadcast.bind(this.visTvprogram))})},onSubmitSearch:function(t,n,s,r,l){return L(this,null,function*(){let c=l.target,a=c.dataset.instance||"",h=c.dataset.dp||"";l.preventDefault();let p=$(c).find('[name="tvsearch"]').val(),v=$(c).find('[name="tvcategory"]').val(),k=$(c).find('[name="tvfrom"]').val();if(!this.parseDatestring(k))return!1;let C=this.visTvprogram.getConfigChannelfilter(h);C.length==0&&(C=this.visTvprogram.channels.reduce((o,i,O)=>(O<4&&o.push(i.id),o),[])),this.searchdata[h]||(this.searchdata[h]={}),this.searchdata[h][t]=Object.assign(this.searchdata[h][t],{datefrom:k,categoryfilter:[v],textfilter:p});let A=new Date,M=this.parseDatestring(k);A.getDate()==M.getDate()&&A.getMonth()==M.getMonth()&&A.getFullYear()==M.getFullYear()?(M.setHours(A.getHours()),M.setMinutes(A.getMinutes()),M.setSeconds(A.getSeconds())):(M.setHours(0),M.setMinutes(0),M.setSeconds(0));let m=new Date(A);m.setDate(m.getDate()+10);let H={channelfilter:C,datefrom:M,datetill:m,categoryfilter:v==""?[]:[parseInt(v)],textfilter:p,maxresults:this.searchdata[h][t].maxresults};if(p==""&&v=="")return!1;this.searchresult[h][t]=yield this.visTvprogram.getServerBroadcastFindAsync(a,H),this.createWidget(t,n,s,r)})},parseDatestring:function(t){let n=t.split(/\D/),s=new Date(n[0],--n[1],n[2]);return s&&s.getMonth()==n[1]?s:!1},onChange:function(t,n,s,r,l,c,a){let h=c.type.split(".");(h[3]=="config"||h[3]=="favorites"||h[3]=="channelfilter"||h[3]=="show")&&h[4]=="val"&&(console.log(`changed ${t} type:${c.type} val:${a}`),this.createWidget(t,n,s,r))}},control:{visTvprogram:null,bound:{},programdata:{},favorites:void 0,timer:{},createWidget:function(t,n,s,r){return L(this,null,function*(){let l=$(`#${t}`);if(!l.length)return setTimeout(function(){vis.binds.tvprogram.control.createWidget(t,n,s,r)},100);if(console.log("createWidget control start"),this.visTvprogram=vis.binds.tvprogram,!s.tvprogram_oid||s.tvprogram_oid=="")return;let[c,a]=this.visTvprogram.getInstanceInfo(s.tvprogram_oid);if(!a&&!c||(this.visTvprogram.categories=yield this.visTvprogram.loadCategories(c,t),this.visTvprogram.channels=yield this.visTvprogram.loadChannels(c,t),this.visTvprogram.channels.length==0||this.visTvprogram.categories.length==0))return;let h=this.visTvprogram.realBackgroundColor($(`#${t}`)[0]);this.visTvprogram.checkStyle("background-color",$(`#${t}`)[0].style.cssText)==""&&$(`#${t}`).css("background-color",h);let p=this.visTvprogram.getConfigChannelfilter(a);p.length==0&&(p=this.visTvprogram.channels.reduce((x,w,V)=>(V<4&&x.push(w.id),x),[]));let v=s.tvprogram_time||"";this.programdata[a]||(this.programdata[a]={});let k=this.parseTime(v);this.programdata[a][t]=yield this.visTvprogram.getServerBroadcastRangeAsync(c,p,k,k),this.bound[a]||(this.bound[a]={}),this.bound[a][t]||(this.bound[a][t]=!1),a&&!this.bound[a][t]&&(vis.editMode||(this.bound[a][t]=!0,vis.binds.tvprogram.bindStates(l,[`${a}.config`,`${a}.favorites`,`${a}.channelfilter`],this.onChange.bind(this,t,n,s,r,a))));let C=parseInt(s.tvprogram_heightRow)||35,A=parseInt(s.tvprogram_broadcastfontpercent)||75,M=s.tvprogram_highlightcolor||"yellow",m=s.tvprogram_showpictures||!1,H=s.tvprogram_dialogwidthpercent/100||.9,o=s.tvprogram_dialogheightpercent/100||.9;$(`#${t}broadcastdlg`).data({dialogwidthpercent:H,dialogheightpercent:o});let i="";i+=`<style> 
`,i+=`#${t} * {
`,i+=`   box-sizing: border-box; 
`,i+=`} 
`,i+=`#${t} .tv-control {
`,i+=`   width: 100%; 
`,i+=`   height: 100%; 
`,i+=`   white-space:nowrap; 
`,i+=`   display:flex; 
`,i+=`   flex-direction: column; 
`,i+=`   overflow: hidden; 
`,i+=`   overflow-y: auto; 
`,i+=`} 
`,i+=`#${t} .tv-row {
`,i+=`   margin: 0px; 
`,i+=`   padding: 0px; 
`,i+=`   width: 100%; 
`,i+=`} 
`,i+=`#${t} .tv-control .tv-row:nth-child(odd) {
`,i+=`   background-color: rgba(128,127,127,.65); 
`,i+=`   padding: 0px; 
`,i+=`} 
`,i+=`#${t} .tv-control .tv-row:nth-child(even) {
`,i+=`   background-color: rgba(128,127,127,.55); 
`,i+=`   padding: 0px; 
`,i+=`} 
`,i+=`#${t} .tv-item {
`,i+=`   display: inline-block; 
`,i+=`   vertical-align: middle; 
`,i+=`   border: solid #80808033; 
`,i+=`   border-width:1px 0px 0px 1px; 
`,i+=`} 
`,i+=`#${t} .channel {
`,i+=`   width: ${C}px; 
`,i+=`   height: ${C}px; 
`,i+=`   padding: 1px; 
`,i+=`   background-color: ${h}; 
`,i+=`} 
`,i+=`#${t} .broadcast {
`,i+=`   height: ${C}px; 
`,i+=`   padding: 3px; 
`,i+=`   font-size: ${A}%; 
`,i+=`   overflow: hidden; 
`,i+=`   width: 100%; 
`,i+=`} 
`,i+=`#${t} .broadcastelement {
`,i+=`   width: 100%; 
`,i+=`   height: 100%; 
`,i+=`   display: table-cell; 
`,i+=`} 
`,i+=`#${t} .broadcastelement .star  {
`,i+=`   display: inline-block; 
`,i+=`   margin: 0px 2px; 
`,i+=`} 
`,i+=`#${t} .broadcastelement .star svg {
`,i+=`   height: 1em; 
`,i+=`   width: 1em; 
`,i+=`   position: relative; 
`,i+=`   top: .125em; 
`,i+=`} 
`,i+=`#${t} .broadcastelement.selected .star svg path {
`,i+=`   color: ${M}; 
`,i+=`} 
`,i+=`#${t} .broadcastelement.selected {
`,i+=`   color: ${M}; 
`,i+=`} 
`,i+=`#${t} .broadcastimage {
`,i+=`   height: ${C-7}px; 
`,i+=`   padding-right: 3px; 
`,i+=`   float: left; 
`,i+=`} 
`,i+=`.${t}.no-titlebar .ui-dialog-titlebar {
`,i+=`   display:none; 
`,i+=`} 
`,i+=`#${t}broadcastdlg  {
`,i+=`   z-index:12; 
`,i+=`} 
`,i+=`#${t}broadcastdlg .event-container.tv-dlg-row {
`,i+=`   height:100%; 
`,i+=`   display:flex; 
`,i+=`   flex-direction:row; 
`,i+=`   overflow:hidden; 
`,i+=`} 
`,i+=`#${t}broadcastdlg .event-container.tv-dlg-col {
`,i+=`   height:100%; 
`,i+=`   display:flex; 
`,i+=`   flex-direction:column; 
`,i+=`   overflow:hidden; 
`,i+=`   font-size:75%; 
`,i+=`} 
`,i+=`#${t}broadcastdlg .event-picture.tv-dlg-row {
`,i+=`   width:50%; 
`,i+=`} 
`,i+=`#${t}broadcastdlg .event-picture.tv-dlg-col {
`,i+=`   height:30%; 
`,i+=`} 
`,i+=`#${t}broadcastdlg .event-data {
`,i+=`   overflow-y:auto; 
`,i+=`} 
`,i+=`#${t}broadcastdlg .event-picture img {
`,i+=`   width:auto; 
`,i+=`   height:auto; 
`,i+=`   max-width:100%; 
`,i+=`   max-height:100%; 
`,i+=`   display:block; 
`,i+=`   margin:auto; 
`,i+=`} 
`,i+=`#${t}broadcastdlg .event-picture img {
`,i+=`   width:auto; 
`,i+=`   height:auto; 
`,i+=`   max-width:100%; 
`,i+=`   max-height:100%; 
`,i+=`   display:block; 
`,i+=`   margin:auto; 
`,i+=`} 
`,i+=`#${t}broadcastdlg .dialogcolumn.tv-dlg-row {
`,i+=`   flex:1; 
`,i+=`   padding:5px; 
`,i+=`} 
`,i+=`#${t}broadcastdlg .dialogcolumn.tv-dlg-col {
`,i+=`   padding:5px; 
`,i+=`} 
`,i+=`#${t}broadcastdlg .button {
`,i+=`   display:inline-block; 
`,i+=`   width: 35px; 
`,i+=`   height: 35px; 
`,i+=`   vertical-align: middle; 
`,i+=`   position: relative; 
`,i+=`   float: right; 
`,i+=`} 
`,i+=`#${t}broadcastdlg .star.selected svg  {
`,i+=`   filter: drop-shadow( 2px 2px 2px rgba(0, 0, 0, .7))
`,i+=`} 
`,i+=`#${t} .broadcastelement.selected .star svg path, #${t}broadcastdlg .star.selected {
`,i+=`   color: ${M}; 
`,i+=`} 
`,i+=`</style> 
`,i+='  <div class="svgcontainer">',i+='<svg style="display:none;"><symbol id="star-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" /></symbol></svg>',i+='<svg style="display:none;"><symbol id="copy-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M19,21H8V7H19M19,5H8A2,2 0 0,0 6,7V21A2,2 0 0,0 8,23H19A2,2 0 0,0 21,21V7A2,2 0 0,0 19,5M16,1H4A2,2 0 0,0 2,3V17H4V3H16V1Z" /></symbol></svg>',i+='<svg style="display:none;"><symbol id="switch-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M21,3H3C1.89,3 1,3.89 1,5V17A2,2 0 0,0 3,19H8V21H16V19H21A2,2 0 0,0 23,17V5C23,3.89 22.1,3 21,3M21,17H3V5H21M16,11L9,15V7" /></symbol></svg>',i+='<svg style="display:none;"><symbol id="record-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12.5,5A7.5,7.5 0 0,0 5,12.5A7.5,7.5 0 0,0 12.5,20A7.5,7.5 0 0,0 20,12.5A7.5,7.5 0 0,0 12.5,5M7,10H9A1,1 0 0,1 10,11V12C10,12.5 9.62,12.9 9.14,12.97L10.31,15H9.15L8,13V15H7M12,10H14V11H12V12H14V13H12V14H14V15H12A1,1 0 0,1 11,14V11A1,1 0 0,1 12,10M16,10H18V11H16V14H18V15H16A1,1 0 0,1 15,14V11A1,1 0 0,1 16,10M8,11V12H9V11" /></symbol></svg>',i+="  </div>";let O,j=this.visTvprogram.getConfigFavorites(a);this.programdata[a][t].map(x=>{x.events.map(w=>{let V=this.visTvprogram.getDate(w.startTime,0),e=this.visTvprogram.channels.find(P=>P.id==w.channel);O=j.indexOf(w.title)>-1,i+='    <ul class="tv-row">',i+='       <li class="tv-item channel">',i+=`          <img width="100%" height="100%" data-channelid="${e.channelId}" data-dp="${a}" src="https://tvfueralle.de/channel-logos/${e.channelId}.png" alt="" class="channel-logo"  onclick="vis.binds.tvprogram.onclickChannelSwitch(this,event)">`,i+="       </li>",i+='       <li class="tv-item broadcast">',i+=`             <div class="broadcastelement ${O?"selected":""}" data-widgetid="${t}" data-eventid="${w.id}" data-viewdate="${V}" data-instance="${c}" data-dp="${a}" data-view="${n}" onclick="vis.binds.tvprogram.onclickBroadcast(this)">`,w.photo.url&&m&&(i+=`<div><img class="broadcastimage" src="https://tvfueralle.de${w.photo.url}"></div>`),i+='                 <div class="broadcasttitle">',i+=`                     ${w.title}`,i+=`                     <div class="star" data-viewdate="${V}" data-eventid="${w.id}" data-instance="${c}" data-dp="${a}" onclick="return vis.binds.tvprogram.onclickFavorite(this,event)"><svg width="100%" height="100%" ><use xlink:href="#star-icon"></use></svg></div>`,i+="                 </div>";let _=new Date(w.startTime),b=new Date(w.endTime);i+='                 <div class="broadcasttime">',i+=`${`0${_.getHours()}`.slice(-2)}:${`0${_.getMinutes()}`.slice(-2)}`,i+=" - ",i+=`${`0${b.getHours()}`.slice(-2)}:${`0${b.getMinutes()}`.slice(-2)}`,i+="                 </div>",i+="             </div>",i+="       </li>",i+="    </ul>"})}),$(`#${t} .tv-control`).html(i),this.timer[t]||clearInterval(this.timer[t]),this.timer[t]=setTimeout(()=>{vis.binds.tvprogram.control.createWidget(t,n,s,r)},1e3*60*5)})},parseTime:function(t){let n,s,r=new Date(t);if(r instanceof Date&&!isNaN(r))return r;if(t=="")return new Date;let l=t.split("/"),c=120;return l.length>1&&parseInt(l[1].trim())>0&&(c=parseInt(l[1].trim())),l=l[0].split(":"),s=new Date,s.setHours(parseInt(l[0])),s.setMinutes(parseInt(l[1])),s.setSeconds(0),n=new Date(s),s.setMinutes(s.getMinutes()+c),new Date<s?n:n.setDate(n.getDate()+1)},onChange:function(t,n,s,r,l,c,a){let h=c.type.split(".");(h[3]=="config"||h[3]=="favorites"||h[3]=="channelfilter"||h[3]=="show")&&h[4]=="val"&&(console.log(`changed ${t} type:${c.type} val:${a}`),this.tvprogram=[],this.createWidget(t,n,s,r))}},favorites:{visTvprogram:null,pending:{},bound:{},favorites:void 0,timer:{},createWidget:function(t,n,s,r){return L(this,null,function*(){let l=$(`#${t}`);if(!l.length)return setTimeout(function(){vis.binds.tvprogram.favorites.createWidget(t,n,s,r)},100);console.log("createWidget start"),this.visTvprogram=vis.binds.tvprogram;let c=s.tvprogram_showweekday||!1,a=s.tvprogram_maxfavorites||10,h=s.tvprogram_highlightcolor||"yellow",p=s.tvprogram_channelname||!1,v,k,C={weekday:"short"},A={month:"2-digit",day:"2-digit"},M={hour:"2-digit",minute:"2-digit"};if(!s.tvprogram_oid||(v=vis.binds.tvprogram.getTvprogramId(s.tvprogram_oid.trim()))==!1||!s.tvprogram_oid||(k=vis.binds.tvprogram.getInstance(s.tvprogram_oid.trim()))==!1)return;let m=this.visTvprogram.realBackgroundColor($(`#${t}`)[0]);this.visTvprogram.checkStyle("background-color",$(`#${t}`)[0].style.cssText)==""&&$(`#${t}`).css("background-color",m),this.bound[v]||(this.bound[v]={}),this.bound[v][t]||(this.bound[v][t]=!1),v&&!this.bound[v][t]&&(vis.editMode||(this.bound[v][t]=!0,vis.binds.tvprogram.bindStates(l,[`${v}.config`,`${v}.favorites`],this.onChange.bind(this,t,n,s,r,v))));let H=this.visTvprogram.getConfigFavorites(v);if(!this.favorites||!this.favorites[v]&&H){let i=yield this.visTvprogram.getFavoritesDataAsync(k,H);this.favorites||(this.favorites=[]),this.favorites[v]=i,this.createWidget(t,n,s,r)}if(!this.favorites||!this.favorites[v])return;let o="";o+=`<style> 
`,o+=`#${t} .tv-fav {
`,o+=`   width: 100%;
`,o+=`} 
`,o+=`#${t} .tv-fav td{
`,o+=`   white-space: nowrap;
`,o+=`} 
`,o+=`#${t} .tv-left {
`,o+=`   text-align: left;
`,o+=`   width: 1%;
`,o+=`} 
`,o+=`#${t} .tv-full {
`,o+=`   width: 50%;
`,o+=`} 
`,o+=`#${t} .tv-fav .star {
`,o+=`   width: 1em;
`,o+=`   height: 1em;
`,o+=`   color: ${h}; 
`,o+=`} 
`,o+=`#${t} .tv-center {
`,o+=`   text-align: center;
`,o+=`   width: 1%;
`,o+=`} 
`,o+=`#${t} .tv-icon {
`,o+=`   height: 1em; 
`,o+=`   width: 1em; 
`,o+=`} 
`,o+=`</style> 
`,o+='  <div class="svgcontainer">',o+='<svg style="display:none;"><symbol id="star-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" /></symbol></svg>',o+="  </div>",o+='<table class="tv-fav">',this.favorites[v]=this.favorites[v].filter(i=>new Date(i.endTime)>=new Date),this.favorites[v].forEach(function(i,O){let j=new Date,x=new Date(i.startTime),w=new Date(i.endTime);O<a&&(vis.binds.tvprogram.compareDate(j,x)?o+='        <tr class="tv-today">':o+="        <tr>",o+=`<td class="tv-left" data-viewdate="${i.viewdate}" data-eventid="${i.id}" data-instance="${k}" data-dp="${v}" onclick="return vis.binds.tvprogram.onclickFavorite(this,event)"><div class="star"><svg width="100%" height="100%" ><use xlink:href="#star-icon"></use></svg></div></td>`,c&&(o+=`           <td class="tv-left">${x.toLocaleString(vis.language,C)}</td>`),o+=`           <td class="tv-left">${x.toLocaleString(vis.language,A)}</td>`,o+=`           <td class="tv-left">${x.toLocaleString(vis.language,M)}</td>`,o+='           <td class="tv-left">-</td>',o+=`           <td class="tv-left">${w.toLocaleString(vis.language,M)}</td>`,p?o+=`           <td class="tv-left">${i.channelname}</td>`:(o+='           <td class="tv-center tv-tdicon">',o+=`              <img width="100%" height="100%" src="https://tvfueralle.de/channel-logos/${i.channelid}.png" alt="" class="tv-icon">`,o+="           </td>"),o+=`           <td class="tv-full">${i.title}</td>`,o+="        </tr>")}),o+="</table>            ",$(`#${t}`).html(o),this.timer[t]?(clearInterval(this.timer[t]),this.timer[t]=setInterval(vis.binds.tvprogram.favorites.createWidget.bind(this,t,n,s,r),1e3*60)):this.timer[t]=setInterval(vis.binds.tvprogram.favorites.createWidget.bind(this,t,n,s,r),1e3*60)})},onChange:function(t,n,s,r,l,c,a){let h=c.type.split(".");(h[3]=="config"||h[3]=="favorites"||h[3]=="channelfilter"||h[3]=="show")&&h[4]=="val"&&(console.log(`changed ${t} type:${c.type} val:${a}`),this.favorites=[],this.createWidget(t,n,s,r))}},time1:{visTvprogram:null,tvprogram:{},bound:{},timer:{},pending:{},measures:{},scroll:{},today:{},viewday:{},olddata:{},createWidget:function(t,n,s,r){return L(this,null,function*(){let l=$(`#${t}`);if(!l.length)return setTimeout(function(){vis.binds.tvprogram.time1.createWidget(t,n,s,r)},100);if(console.log(`createWidget start ${t}`),this.visTvprogram=vis.binds.tvprogram,!s.tvprogram_oid||s.tvprogram_oid=="")return;let[c,a]=this.visTvprogram.getInstanceInfo(s.tvprogram_oid);if(!a&&!c)return;let h=s.tvprogram_highlightcolor||"yellow";this.olddata[t]||(this.olddata[t]=s),(!this.measures[t]||JSON.stringify(this.olddata[t])!=JSON.stringify(s))&&(this.measures[t]={origwidthItem:parseInt(s.tvprogram_widthItem)||120,timeItem:30,heightRow:parseInt(s.tvprogram_heightRow)||35,scrollbarWidth:this.getScrollbarWidth(),markerpositionpercent:s.tvprogram_markerpositionpercent/100||.25,dialogwidthpercent:s.tvprogram_dialogwidthpercent/100||.9,dialogheightpercent:s.tvprogram_dialogheightpercent/100||.9,showpictures:s.tvprogram_showpictures||!1}),$(`#${t}broadcastdlg`).data({dialogwidthpercent:this.measures[t].dialogwidthpercent,dialogheightpercent:this.measures[t].dialogheightpercent}),this.measures[t].widthItem||(this.measures[t].widthItem=this.measures[t].origwidthItem),((this.today||{})[t]||{}).prevday||$(`#${t} .tv-container`).html("Datapoints loading..."),console.log("Load Data"),this.visTvprogram.categories||(this.visTvprogram.categories=yield this.visTvprogram.loadCategories(c,t)),this.visTvprogram.channels||(this.visTvprogram.channels=yield this.visTvprogram.loadChannels(c,t)),this.visTvprogram.genres||(this.visTvprogram.genres=yield this.visTvprogram.loadGenres(c,t));function p(b){return!b||Object.keys(b)==0}this.today[t]||(this.today[t]={today:new Date,prevday:null}),this.scroll[t]||(this.scroll[t]={time:new Date(0),position:0,marker:0,timeout:null,automatic:0}),console.log("Calc Date");let v=this.visTvprogram.calcDate(this.today[t].today),k=this.visTvprogram.getDate(v,0);this.viewday[t]||(this.viewday[t]={viewday:k,prevday:null}),this.viewday[t].viewday=k;let C=this.visTvprogram.getDate(v,0);if(p(this.tvprogram[k])&&(this.tvprogram[k]=yield this.visTvprogram.loadProgram(c,t,k)),this.visTvprogram.categories.length==0||this.visTvprogram.categories[0]==="request"||this.visTvprogram.channels.length==0||this.visTvprogram.channels[0]==="request"||this.visTvprogram.genres.length==0||this.visTvprogram.genres[0]==="request"||p(this.tvprogram[k]))return;this.viewday[t].viewday!=this.viewday[t].prevday&&(this.viewday[t].prevday=this.viewday[t].viewday),this.bound[a]||(this.bound[a]={}),this.bound[a][t]||(this.bound[a][t]=!1),a&&!this.bound[a][t]&&(vis.editMode||(this.bound[a][t]=!0,vis.binds.tvprogram.bindStates(l,[`${a}.config`,`${a}.cmd`,`${a}.favorites`,`${a}.channelfilter`,`${a}.show`],this.onChange.bind(this,t,n,s,r,c)))),this.onclickChannelSave.name=="onclickChannelSave"&&(this.onclickChannelSave=this.onclickChannelSave.bind(this)),console.log("Calc Channels");let A=this.visTvprogram.getConfigChannelfilter(a);A.length==0&&(A=this.visTvprogram.channels.reduce((b,P,R)=>(R<4&&b.push(P.id),b),[])),console.log("Calc styles");let M=this.measures[t].widthItem,m=this.measures[t].heightRow,H=this.measures[t].heightRow,o=this.visTvprogram.realBackgroundColor($(`#${t}`)[0]);this.visTvprogram.checkStyle("background-color",$(`#${t}`)[0].style.cssText)==""&&$(`#${t}`).css("background-color",o);let i=48*M+m,O=s.tvprogram_headerfontpercent||125,j=s.tvprogram_broadcastfontpercent||75,x=0,w=$(`#${t}`).height()-H,V=(A.length+1)*H;V<w?x=V:x=w-this.measures[t].scrollbarWidth,console.log(`Display day:${k}`),console.log("Output CSS");let e="";e+=`<style> 
`,e+=`#${t} * {
`,e+=`   box-sizing: border-box; 
`,e+=`} 
`,e+=`#${t} .tv-container {
`,e+=`   width: 100%; 
`,e+=`   height: 100%; 
`,e+=`   white-space:nowrap; 
`,e+=`   display:flex; 
`,e+=`   flex-direction: column; 
`,e+=`} 
`,e+=`#${t} .navcontainer {
`,e+=`   width: 100%; 
`,e+=`} 
`,e+=`#${t} .scrollcontainer {
`,e+=`   flex-grow: 1; 
`,e+=`   overflow:auto; 
`,e+=`   width:100%; 
`,e+=`} 
`,e+=`#${t} .tv-row {
`,e+=`   margin: 0px; 
`,e+=`   padding: 0px; 
`,e+=`   width: ${i}px; 
`,e+=`} 
`,e+=`#${t} .tv-item {
`,e+=`   display: inline-block; 
`,e+=`   vertical-align: middle; 
`,e+=`   border: solid #80808033; 
`,e+=`   border-width:1px 0px 0px 1px; 
`,e+=`} 
`,e+=`#${t} .tv-head-time {
`,e+=`   position:sticky; 
`,e+=`   position: -webkit-sticky; 
`,e+=`   top:0px; 
`,e+=`   z-index:11; 
`,e+=`   background-color: ${o}; 
`,e+=`} 
`,e+=`#${t} .tv-head-left {
`,e+=`   position:sticky; 
`,e+=`   position: -webkit-sticky; 
`,e+=`   left:0; 
`,e+=`   z-index:11; 
`,e+=`   background-color: ${o}; 
`,e+=`} 
`,e+=`#${t} svg rect {
`,e+=`   fill: ${$(`#${t}`).css("color")}; 
`,e+=`} 
`,e+=`#${t} .channel {
`,e+=`   width: ${H}px; 
`,e+=`   height: ${H}px; 
`,e+=`   padding: 1px; 
`,e+=`} 
`,e+=`#${t} .time {
`,e+=`   width: ${M}px; 
`,e+=`   height: ${H}px; 
`,e+=`   font-weight: 700; 
`,e+=`   font-size: ${O}%; 
`,e+=`   padding: 5px 5px; 
`,e+=`} 
`,e+=`#${t} .time:after {
`,e+=`   content:""; 
`,e+=`   display: inline-block; 
`,e+=`   vertical-align:middle; 
`,e+=`   height: 100%; 
`,e+=`} 
`,e+=`#${t} .time span {
`,e+=`   vertical-align:middle; 
`,e+=`} 
`,e+=`#${t} .broadcast {
`,e+=`   height: ${H}px; 
`,e+=`   padding: 3px; 
`,e+=`   font-size: ${j}%; 
`,e+=`   overflow: hidden; 
`,e+=`} 
`,e+=`#${t} .broadcastelement {
`,e+=`   width: 100%; 
`,e+=`   height: 100%; 
`,e+=`   display: table-cell; 
`,e+=`} 
`,e+=`#${t} .broadcastelement.hide {
`,e+=`   display: none; 
`,e+=`} 
`,e+=`#${t} .broadcastelement .star  {
`,e+=`   display: inline-block; 
`,e+=`   margin: 0px 2px; 
`,e+=`} 
`,e+=`#${t} .broadcastelement .star svg {
`,e+=`   height: 1em; 
`,e+=`   width: 1em; 
`,e+=`   position: relative; 
`,e+=`   top: .125em; 
`,e+=`} 
`,e+=`#${t}broadcastdlg .star.selected svg  {
`,e+=`   filter: drop-shadow( 2px 2px 2px rgba(0, 0, 0, .7))
`,e+=`} 
`,e+=`#${t} .broadcastelement.selected .star svg path, #${t}broadcastdlg .star.selected {
`,e+=`   color: ${h}; 
`,e+=`} 
`,e+=`#${t} .broadcastelement.selected {
`,e+=`   color: ${h}; 
`,e+=`   background-color: ${this.visTvprogram.colorToRGBA(h,".1")}; 
`,e+=`} 
`,e+=`#${t} .broadcastimage {
`,e+=`   height: ${H-7}px; 
`,e+=`   padding-right: 3px; 
`,e+=`   float: left; 
`,e+=`} 
`,e+=`#${t} .button {
`,e+=`   display:inline-block; 
`,e+=`   width: ${H}px; 
`,e+=`   height: ${H}px; 
`,e+=`   background-color: ${o}; 
`,e+=`   vertical-align: middle; 
`,e+=`   padding: 5px 5px; 
`,e+=`} 
`,e+=`#${t} .dateinfo {
`,e+=`   height: ${H}px; 
`,e+=`   padding: 5px 5px; 
`,e+=`   position: absolute; 
`,e+=`   right: 0px; 
`,e+=`   border: 0px; 
`,e+=`} 
`,e+=`#${t} .dateinfo:after {
`,e+=`   content:""; 
`,e+=`   display: inline-block; 
`,e+=`   vertical-align:middle; 
`,e+=`   height: 100%; 
`,e+=`} 
`,e+=`#${t} .dateinfo span {
`,e+=`   vertical-align:middle; 
`,e+=`} 
`,e+=`.ui-dialog.${t} {
`,e+=`   z-index:12; 
`,e+=`} 
`,e+=`.clearfix {
`,e+=`   clear:both; 
`,e+=`   content:""; 
`,e+=`   display:table; 
`,e+=`} 
`,e+=`#${t}channeldlg .chselect-container {
`,e+=`} 
`,e+=`#${t}channeldlg ul.channel {
`,e+=`   margin:0px; 
`,e+=`   padding:0px; 
`,e+=`} 
`,e+=`#${t}channeldlg .listitem  {
`,e+=`   float: left; 
`,e+=`} 
`,e+=`#${t}channeldlg .listitem .channel {
`,e+=`   list-style: none; 
`,e+=`} 
`,e+=`#${t}channeldlg .items  {
`,e+=`   list-style: none; 
`,e+=`   margin:0px; 
`,e+=`   padding:0px; 
`,e+=`} 
`,e+=`#${t}channeldlg .channel {
`,e+=`   margin:5px; 
`,e+=`   width: ${H*1.5}px; 
`,e+=`   height: ${H*1.5}px; 
`,e+=`   list-style: none; 
`,e+=`} 
`,e+=`#${t}channeldlg .items .channel[selected] {
`,e+=`   background-color:lightgray; 
`,e+=`} 
`,e+=`.${t}.no-titlebar .ui-dialog-titlebar {
`,e+=`   display:none; 
`,e+=`} 
`,e+=`#${t}broadcastdlg  {
`,e+=`   z-index:12; 
`,e+=`} 
`,e+=`#${t}broadcastdlg .event-container.tv-dlg-row {
`,e+=`   height:100%; 
`,e+=`   display:flex; 
`,e+=`   flex-direction:row; 
`,e+=`   overflow:hidden; 
`,e+=`} 
`,e+=`#${t}broadcastdlg .event-container.tv-dlg-col {
`,e+=`   height:100%; 
`,e+=`   display:flex; 
`,e+=`   flex-direction:column; 
`,e+=`   overflow:hidden; 
`,e+=`   font-size:75%; 
`,e+=`} 
`,e+=`#${t}broadcastdlg .event-picture.tv-dlg-row {
`,e+=`   width:50%; 
`,e+=`} 
`,e+=`#${t}broadcastdlg .event-picture.tv-dlg-col {
`,e+=`   height:30%; 
`,e+=`} 
`,e+=`#${t}broadcastdlg .event-data {
`,e+=`   overflow-y:auto; 
`,e+=`} 
`,e+=`#${t}broadcastdlg .event-picture img {
`,e+=`   width:auto; 
`,e+=`   height:auto; 
`,e+=`   max-width:100%; 
`,e+=`   max-height:100%; 
`,e+=`   display:block; 
`,e+=`   margin:auto; 
`,e+=`} 
`,e+=`#${t}broadcastdlg .event-picture img {
`,e+=`   width:auto; 
`,e+=`   height:auto; 
`,e+=`   max-width:100%; 
`,e+=`   max-height:100%; 
`,e+=`   display:block; 
`,e+=`   margin:auto; 
`,e+=`} 
`,e+=`#${t}broadcastdlg .dialogcolumn.tv-dlg-row {
`,e+=`   flex:1; 
`,e+=`   padding:5px; 
`,e+=`} 
`,e+=`#${t}broadcastdlg .dialogcolumn.tv-dlg-col {
`,e+=`   padding:5px; 
`,e+=`} 
`,e+=`#${t}broadcastdlg .button {
`,e+=`   display:inline-block; 
`,e+=`   width: 35px; 
`,e+=`   height: 35px; 
`,e+=`   vertical-align: middle; 
`,e+=`   position: relative; 
`,e+=`   float: right; 
`,e+=`} 
`,e+=`#${t} .tooltip {
`,e+=`   position: relative; 
`,e+=`} 
`,e+=`#${t} .tooltip span[role=tooltip] {
`,e+=`   display: none; 
`,e+=`} 
`,e+=`#${t} .tooltip:hover span[role=tooltip] {
`,e+=`   display: block; 
`,e+=`   position: absolute; 
`,e+=`   left: 3em; 
`,e+=`   border: 1px solid; 
`,e+=`   font-size: 75%; 
`,e+=`   padding: 0.2em; 
`,e+=`   z-index: 100; 
`,e+=`   background-color: ${o}; 
`,e+=`} 
`,e+=`#${t} .scrollcontainer ul.tv-row:nth-child(odd)> li.broadcast:nth-child(odd),#${t} ul.tv-row:nth-child(odd)> li.time:nth-child(odd) {
`,e+=`   background-color: rgba(128, 128, 128, 0.65); 
`,e+=`} 
`,e+=`#${t} .scrollcontainer ul.tv-row:nth-child(odd)> li.broadcast:nth-child(even),#${t} ul.tv-row:nth-child(odd)> li.time:nth-child(even) {
`,e+=`   background-color: rgba(128, 128, 128, 0.55); 
`,e+=`} 
`,e+=`#${t} .scrollcontainer ul.tv-row:nth-child(even)> li.broadcast:nth-child(odd) {
`,e+=`   background-color: rgba(128, 128, 128, 0.45); 
`,e+=`} 
`,e+=`#${t} .scrollcontainer ul.tv-row:nth-child(even)> li.broadcast:nth-child(even) {
`,e+=`   background-color: rgba(128, 128, 128, 0.35); 
`,e+=`} 
`,e+=`#${t} .line {
`,e+=`   position: absolute; 
`,e+=`   top: 0; 
`,e+=`   width: 2px; 
`,e+=`   background-color: red; 
`,e+=`   opacity: 0.8; 
`,e+=`   z-index: 10; 
`,e+=`   height: ${x}px; 
`,e+=`   float: left; 
`,e+=`} 
`,e+=`#${t} .disable-select {
`,e+=`   -webkit-user-select: none; 
`,e+=`   -moz-user-select: none; 
`,e+=`   -ms-user-select: none; 
`,e+=`   -user-select: none; 
`,e+=`} 
`,e+=`#${t} .staricon {
`,e+=`     background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100%' height='100%' viewBox='0 0 24 24'><path fill='currentColor' d='M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z' /></svg>"); 
`,e+=`} 
`,e+=`</style> 
`,console.log("Output SVG"),e+='  <div class="svgcontainer">',e+='<svg style="display:none;"><symbol id="star-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="check-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"></path></symbol></svg>',e+='<svg style="display:none;"><symbol id="cancel-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"></path></symbol></svg>',e+='<svg style="display:none;"><symbol id="copy-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M19,21H8V7H19M19,5H8A2,2 0 0,0 6,7V21A2,2 0 0,0 8,23H19A2,2 0 0,0 21,21V7A2,2 0 0,0 19,5M16,1H4A2,2 0 0,0 2,3V17H4V3H16V1Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="switch-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M21,3H3C1.89,3 1,3.89 1,5V17A2,2 0 0,0 3,19H8V21H16V19H21A2,2 0 0,0 23,17V5C23,3.89 22.1,3 21,3M21,17H3V5H21M16,11L9,15V7" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="burger-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M3,6H21V8H3V6M3,11H21V13H3V11M3,16H21V18H3V16Z"></path></symbol></svg>',e+='<svg style="display:none;"><symbol id="nav-prevD-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M20,9V15H12V19.84L4.16,12L12,4.16V9H20Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="nav-center-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4M12,9A3,3 0 0,0 9,12A3,3 0 0,0 12,15A3,3 0 0,0 15,12A3,3 0 0,0 12,9Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="nav-nextD-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M4,15V9H12V4.16L19.84,12L12,19.84V15H4Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="zoom-minus-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M15.5,14H14.71L14.43,13.73C15.41,12.59 16,11.11 16,9.5A6.5,6.5 0 0,0 9.5,3A6.5,6.5 0 0,0 3,9.5A6.5,6.5 0 0,0 9.5,16C11.11,16 12.59,15.41 13.73,14.43L14,14.71V15.5L19,20.5L20.5,19L15.5,14M9.5,14C7,14 5,12 5,9.5C5,7 7,5 9.5,5C12,5 14,7 14,9.5C14,12 12,14 9.5,14M7,9H12V10H7V9Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="zoom-center-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12,9A3,3 0 0,0 9,12A3,3 0 0,0 12,15A3,3 0 0,0 15,12A3,3 0 0,0 12,9M19,19H15V21H19A2,2 0 0,0 21,19V15H19M19,3H15V5H19V9H21V5A2,2 0 0,0 19,3M5,5H9V3H5A2,2 0 0,0 3,5V9H5M5,15H3V19A2,2 0 0,0 5,21H9V19H5V15Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="zoom-plus-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M15.5,14L20.5,19L19,20.5L14,15.5V14.71L13.73,14.43C12.59,15.41 11.11,16 9.5,16A6.5,6.5 0 0,1 3,9.5A6.5,6.5 0 0,1 9.5,3A6.5,6.5 0 0,1 16,9.5C16,11.11 15.41,12.59 14.43,13.73L14.71,14H15.5M9.5,14C12,14 14,12 14,9.5C14,7 12,5 9.5,5C7,5 5,7 5,9.5C5,12 7,14 9.5,14M12,10H10V12H9V10H7V9H9V7H10V9H12V10Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="record-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12.5,5A7.5,7.5 0 0,0 5,12.5A7.5,7.5 0 0,0 12.5,20A7.5,7.5 0 0,0 20,12.5A7.5,7.5 0 0,0 12.5,5M7,10H9A1,1 0 0,1 10,11V12C10,12.5 9.62,12.9 9.14,12.97L10.31,15H9.15L8,13V15H7M12,10H14V11H12V12H14V13H12V14H14V15H12A1,1 0 0,1 11,14V11A1,1 0 0,1 12,10M16,10H18V11H16V14H18V15H16A1,1 0 0,1 15,14V11A1,1 0 0,1 16,10M8,11V12H9V11" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="hide-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M2,5.27L3.28,4L20,20.72L18.73,22L15.65,18.92C14.5,19.3 13.28,19.5 12,19.5C7,19.5 2.73,16.39 1,12C1.69,10.24 2.79,8.69 4.19,7.46L2,5.27M12,9A3,3 0 0,1 15,12C15,12.35 14.94,12.69 14.83,13L11,9.17C11.31,9.06 11.65,9 12,9M12,4.5C17,4.5 21.27,7.61 23,12C22.18,14.08 20.79,15.88 19,17.19L17.58,15.76C18.94,14.82 20.06,13.54 20.82,12C19.17,8.64 15.76,6.5 12,6.5C10.91,6.5 9.84,6.68 8.84,7L7.3,5.47C8.74,4.85 10.33,4.5 12,4.5M3.18,12C4.83,15.36 8.24,17.5 12,17.5C12.69,17.5 13.37,17.43 14,17.29L11.72,15C10.29,14.85 9.15,13.71 9,12.28L5.6,8.87C4.61,9.72 3.78,10.78 3.18,12Z" /></symbol></svg>',e+="  </div>",console.log("Output Navigation"),e+='  <div class="navcontainer">',e+='    <ul class="tv-row tv-head-top">',e+=this.getButtonHeader(k).join(""),e+="    </ul>",e+="  </div>",console.log("Output tvprogram"),e+='  <div class="scrollcontainer">',e+='    <ul class="tv-row tv-head-time">',e+='      <div class="line"></div>',e+='      <li class="tv-item tv-head-left channel">',e+="      </li>",e+=this.getTimetable().join(""),e+="    </ul>",this.getEvents(this.tvprogram[C],A).map(b=>{e+='    <ul class="tv-row">',e+=this.getBroadcasts4Channel(b,t,n,C,a,c).join(""),e+="    </ul>"}),$(`#${t} .tv-container`).html(e),this.visTvprogram.getConfigShow(a)==1?$(`#${t} .broadcastelement:not(".selected") > *`).show():$(`#${t} .broadcastelement:not(".selected") > *`).hide(),console.log("Connect Buttone events"),$(`#${t} .burger`).click(function(b,P,R,y){vis.binds.tvprogram.time1.onclickChannel(b,R,P,y)}.bind(this,t,a,c)),$(`#${t} .button.nav.prevD`).off("click.onClickDay").on("click.onClickDay",this.onClickDay.bind(this,t,n,s,r)),$(`#${t} .button.nav.nextD`).off("click.onClickDay").on("click.onClickDay",this.onClickDay.bind(this,t,n,s,r)),$(`#${t} .button.nav.center`).off("click.onClickDay").on("click.onClickDay",this.onClickDay.bind(this,t,n,s,r)),$(`#${t} .button.zoom.minus`).off("click.onClickZoom").on("click.onClickZoom",this.onClickZoom.bind(this,t,n,s,r)),$(`#${t} .button.zoom.plus`).off("click.onClickZoom").on("click.onClickZoom",this.onClickZoom.bind(this,t,n,s,r)),$(`#${t} .button.zoom.center`).off("click.onClickZoom").on("click.onClickZoom",this.onClickZoom.bind(this,t,n,s,r)),$(`#${t} .button.hide`).off("click.onClickHide").on("click.onClickHide",this.onClickHide.bind(this,c,a,t)),$(`#${t} .scrollcontainer`).scroll(function(b){this.scroll[b].automatic==0&&(this.scroll[b].automatic=2),this.scroll[b].time=new Date,this.calcScroll(b)}.bind(this,t)),this.visTvprogram.copyStyles("font",$(`#${t}`).get(0),$(`#${t}broadcastdlg`).get(0)),this.visTvprogram.copyStyles("color",$(`#${t}`).get(0),$(`#${t}broadcastdlg`).get(0)),this.visTvprogram.copyStyles("background-color",$(`#${t}`).get(0),$(`#${t}broadcastdlg`).get(0)),this.updateMarker(t,this.today[t].today),this.timer[t]?(clearInterval(this.timer[t]),this.timer[t]=setInterval(this.updateMarker.bind(this,t,this.today[t].today),15e3)):this.timer[t]=setInterval(this.updateMarker.bind(this,t,this.today[t].today),15e3),this.scroll[t].position==0?(this.calcScroll(t),this.setScroll(t)):this.setScroll(t),console.log("Output done")})},onClickHide:function(t,n){this.visTvprogram.toggleShow(t,n)},onClickZoom:function(t,n,s,r,l){$(l.currentTarget).hasClass("plus")&&(this.measures[t].widthItem=this.measures[t].widthItem+this.measures[t].origwidthItem/4,console.log("Click Zoom plus")),$(l.currentTarget).hasClass("minus")&&(this.measures[t].widthItem=this.measures[t].widthItem-this.measures[t].origwidthItem/4,console.log("Click Zoom minus")),$(l.currentTarget).hasClass("center")&&(this.measures[t].widthItem=this.measures[t].origwidthItem,console.log("Click Zoom center")),this.measures[t].widthItem<20&&(this.measures[t].widthItem=this.measures[t].origwidthItem,console.log("Click Zoom Max zoom reached, reset")),this.calcScroll(t),this.createWidget(t,n,s,r)},onClickDay:function(t,n,s,r,l){console.log(`ClickNav:${$(l.currentTarget).attr("class")}`);let c=0;$(l.currentTarget).hasClass("prevD")&&(c=-1),$(l.currentTarget).hasClass("nextD")&&(c=1);let a=K(this.today[t].today).add(c,"day"),h=K(a).diff(K(),"day");$(l.currentTarget).hasClass("center")?(this.today[t].today=new Date,this.scroll[t].position=0):h>-5&&h<5&&(this.today[t].prevday=new Date(this.today[t].today),this.today[t].today=a.toDate(),console.log(`Navigate to date: ${K(a).format()}`)),this.scroll[t].time=new Date(0),this.createWidget(t,n,s,r)},calcScroll:function(t){let n=$(`#${t} .scrollcontainer`).get(0);n&&(n.scrollLeft==0||this.scroll[t].position==0?this.scroll[t].position=this.scroll[t].marker/n.scrollWidth:this.scroll[t].position=(n.scrollLeft+n.clientWidth*this.measures[t].markerpositionpercent)/n.scrollWidth)},setScroll:function(t){try{let n=$(`#${t} .scrollcontainer`).get(0);if(!n.scrollWidth)return;n.scrollLeft=this.scroll[t].position*n.scrollWidth-n.clientWidth*this.measures[t].markerpositionpercent}catch(n){console.log(n)}},updateMarker:function(t,n){if(this.scroll[t].automatic==2&&new Date-this.scroll[t].time<90*1e3)return;this.scroll[t].automatic=0,this.visTvprogram.calcDate(n).toLocaleDateString()!=this.visTvprogram.calcDate(new Date).toLocaleDateString()?$(`#${t} .line`).hide():$(`#${t} .line`).show();let s=this.measures[t].widthItem,r=this.measures[t].timeItem,l=this.measures[t].heightRow,c=new Date(this.visTvprogram.calcDate(new Date));c.setHours(5),c.setMinutes(0),c.setSeconds(0);let a=new Date(c);a.setDate(a.getDate()+1);let p=l+Math.floor((new Date-c)/6e4/r*s*10)/10;$(`#${t} .line`).css("left",`${p}px`),this.scroll[t].marker=p,this.scroll[t].position=0,this.calcScroll(t),this.scroll[t].timeout&&clearTimeout(this.scroll[t].timeout),this.scroll[t].automatic=1,this.scroll[t].timeout=window.setTimeout(function(){this.scroll[t].automatic=0,clearTimeout(this.scroll[t].timeout),this.scroll[t].timeout=null}.bind(this),500),this.setScroll(t)},getScrollbarWidth:function(){let t=document.createElement("div");t.className="scrollbar-measure",t.style.cssText="width: 100px;height: 100px;overflow: scroll;position: absolute;top: -9999px;",document.body.appendChild(t);let n=t.offsetWidth-t.clientWidth;return document.body.removeChild(t),n},getChannels:function(t,n=[]){let s=[];return n.map(r=>{let l=t.find(c=>c.id==r);s.push(`<li class="listitem channel" data-order="${l.order}" data-id="${l.id}" selected><img width="100%" height="100%" src="https://tvfueralle.de/channel-logos/${l.channelId}.png" alt="" class="channel-logo"></li>`)}),t.sort((r,l)=>r.order+(n.indexOf(r.id)==-1)*1e5-(l.order+(n.indexOf(l.id)==-1)*1e5)).map(r=>{n.findIndex(l=>l==r.id)==-1&&s.push(`<li class="listitem channel" data-order="${r.order}" data-id="${r.id}"><img width="100%" height="100%" src="https://tvfueralle.de/channel-logos/${r.channelId}.png" alt="" class="channel-logo"></li>`)}),s},onclickChannelSave:function(t,n){let s=t.dataset.widgetid;if(n){let r=t.dataset.dp||"",l=t.dataset.instance||"";this.visTvprogram.setConfigChannelfilter(l,r,$(`#${s}channeldlg .chselect-container .channel[selected]`).toArray().map(c=>parseInt(c.dataset.id)))}$(`#${s}channeldlg`).dialog("close")},onclickChannel:function(t,n,s){let r=!1,l=this.visTvprogram.channels,c=this.visTvprogram.getConfigChannelfilter(s);c.length==0&&(c=l.reduce((h,p,v)=>(v<4&&h.push(p.id),h),[]));let a="";a+='  <div class="chselect-container clearfix">',a+=`    <ul class="listitem channel" data-instance="${n}" data-dp="${s}" data-widgetid="${t}" onclick="vis.binds.tvprogram.time1.onclickChannelSave(this,true)" ><li class="channel"><svg width="100%" height="100%" ><use xlink:href="#check-icon"></use></svg></li></ul>`,a+=`    <ul class="listitem channel" data-widgetid="${t}" onclick="vis.binds.tvprogram.time1.onclickChannelSave(this,false)"><li class="channel"><svg width="100%" height="100%" ><use xlink:href="#cancel-icon"></use></svg></li></ul>`,a+="  </div>",a+='  <div class="chselect-container clearfix sortable">',a+='  <ul class="items">',a+=this.getChannels(l,c).join(`
`),a+="  </ul>",a+="  </div>",$(`#${t}channeldlg`).html(a),$(".chselect-container .items .channel").click(function(){if(console.log("channel click"),r)return;let h=$(this).parent().find("[selected]").last();this.dataset.id&&($(this).attr("selected")?$(this).removeAttr("selected"):$(this).attr("selected","")),$(this).attr("selected")?$(this).insertAfter(h):$(this).parent().children().sort(function(p,v){return p.dataset.order+($(p).attr("selected")!="selected")*1e5-(v.dataset.order+($(v).attr("selected")!="selected")*1e5)}).appendTo($(this).parent())}),$(".chselect-container.sortable").sortable({items:".items .channel[selected]",containment:"parent",revert:!0,grid:[5,5],opacity:.8,tolerance:"pointer",start:function(){r=!0},stop:function(){r=!1}}),$(`#${t}channeldlg`).dialog({resizable:!1,autoOpen:!1,modal:!0,position:{of:$(`#${t}`)},width:$(`#${t}`).width()*this.measures[t].dialogwidthpercent,height:$(`#${t}`).height()*this.measures[t].dialogheightpercent,dialogClass:`no-titlebar ${t}`,zIndex:10003,stack:!1}),this.visTvprogram.copyStyles("font",$(`#${t}`).get(0),$(`#${t}channeldlg`).get(0)),this.visTvprogram.copyStyles("color",$(`#${t}`).get(0),$(`#${t}channeldlg`).get(0)),this.visTvprogram.copyStyles("background-color",$(`#${t}`).get(0),$(`#${t}channeldlg`).get(0)),$(`#${t}channeldlg`).dialog("open")},getBroadcasts4Channel:function(t,n,s,r,l,c){let a=this.measures[n].widthItem,h=this.measures[n].timeItem,p=this.visTvprogram.getConfigFavorites(l),v,k=new Date(t.events[0].airDate);k.setHours(5),k.setMinutes(0);let C=new Date(k);C.setDate(C.getDate()+1);let A=this.visTvprogram.channels.find(i=>i.id==t.channel),M=[],m="";m+='    <li class="tv-item tv-head-left channel">',m+=`      <img width="100%" height="100%" data-instance="${c}" data-channelid="${A.channelId}" data-dp="${l}" src="https://tvfueralle.de/channel-logos/${A.channelId}.png" alt="" class="channel-logo"  onclick="vis.binds.tvprogram.onclickChannelSwitch(this,event)">`,m+="    </li>",M.push(m);for(let i=0;i<t.events.length;i++){let O=t.events[i],j=new Date(O.startTime),x=new Date(O.endTime);j>=C||x<=k||(i==0&&j>k&&M.push(`<li class="tv-item broadcast" style="left:0px; width:${Math.floor((j-k)/6e4/h*a*10)/10}px;"></li>`),j<k&&(j=k),x>C&&(x=C),v=p.indexOf(O.title)>-1,m="",m+='<li class="tv-item broadcast" style="',m+=`left:${Math.floor((j-k)/6e4/h*a*10)/10}px;`,m+=`width:${Math.floor((x-j)/6e4/h*a*10)/10}px;">`,m+=`<div class="broadcastelement ${v?"selected":""}" data-widgetid="${n}" data-eventid="${O.id}" data-viewdate="${r}" data-instance="${c}" data-dp="${l}" data-view="${s}" onclick="vis.binds.tvprogram.onclickBroadcast(this)">`,O.photo.url&&this.measures[n].showpictures&&(m+=`<div><img class="broadcastimage" src="https://tvfueralle.de${O.photo.url}"></div>`),m+=`<div class="broadcasttitle">${O.title}`,m+=`<div class="star" data-viewdate="${r}" data-eventid="${O.id}" data-dp="${l}" data-instance="${c}" onclick="return vis.binds.tvprogram.onclickFavorite(this,event)"><svg width="100%" height="100%" ><use xlink:href="#star-icon"></use></svg></div>`,m+="</div>",m+='<div class="broadcasttime">',m+=`${`0${j.getHours()}`.slice(-2)}:${`0${j.getMinutes()}`.slice(-2)}`,m+=" - ",m+=`${`0${x.getHours()}`.slice(-2)}:${`0${x.getMinutes()}`.slice(-2)}`,m+="</div></div></li>",M.push(m))}let H=new Date(t.events[t.events.length-1].startTime),o=new Date(t.events[t.events.length-1].endTime);return H<C&&o<C&&(H=o,o=C,m="",m+='<li class="tv-item broadcast" style="',m+=`left:${Math.floor((H-k)/6e4/h*a*10)/10}px;`,m+=`width:${Math.floor((o-H)/6e4/h*a*10)/10}px;">`,m+="</li>",M.push(m)),M},getEvents:function(t,n){let s=[],r;return t.map(l=>{(r=n.indexOf(l.channel))>-1&&(s[r]||(s[r]={}),s[r].events||(s[r].events=[]),s[r].channel=l.channel,s[r].events.push(l))}),s},getTimetable:function(){let t=[];for(let n=0;n<24;n++)t.push(`<li class="tv-item time"><span>${`0${n}`.slice(-2)}:00</span></li>`),t.push(`<li class="tv-item time"><span>${`0${n}`.slice(-2)}:30</span></li>`);return[].concat(t.slice(10),t.slice(0,10))},getButtonHeader:function(t){let n=[];return n.push('<li class="tv-item tv-head-topleft tv-head-left button burger tooltip"><span role="tooltip">Menu</span><svg width="100%" height="100%" ><use xlink:href="#burger-icon"></use></svg></li>'),n.push('<li class="tv-item button nav prevD tooltip"><span role="tooltip">Previous day</span><svg width="100%" height="100%" ><use xlink:href="#nav-prevD-icon"></use></svg></li>'),n.push('<li class="tv-item button nav center tooltip"><span role="tooltip">Today</span><svg width="100%" height="100%" ><use xlink:href="#nav-center-icon"></use></svg></li>'),n.push('<li class="tv-item button nav nextD tooltip"><span role="tooltip">Next day</span><svg width="100%" height="100%" ><use xlink:href="#nav-nextD-icon"></use></svg></li>'),n.push('<li class="tv-item button zoom minus tooltip"><span role="tooltip">Zoom in</span><svg width="100%" height="100%" ><use xlink:href="#zoom-minus-icon"></use></svg></li>'),n.push('<li class="tv-item button zoom center tooltip"><span role="tooltip">Zoom normal</span><svg width="100%" height="100%" ><use xlink:href="#zoom-center-icon"></use></svg></li>'),n.push('<li class="tv-item button zoom plus tooltip"><span role="tooltip">Zoom out</span><svg width="100%" height="100%" ><use xlink:href="#zoom-plus-icon"></use></svg></li>'),n.push('<li class="tv-item button hide tooltip"><span role="tooltip">Hide Non-Favorites</span><svg width="100%" height="100%" ><use xlink:href="#hide-icon"></use></svg></li>'),n.push(`<li class="tv-item dateinfo">${new Date(t).toLocaleDateString(navigator.language,{weekday:"short"})}, ${new Date(t).toLocaleDateString()}</li>`),n},onChange:function(t,n,s,r,l,c,a){return L(this,null,function*(){let h=c.type.split(".");if((h[3]=="config"||h[3]=="favorites"||h[3]=="channelfilter"||h[3]=="show")&&h[4]=="val"&&(console.log(`changed ${t} type:${c.type} val:${a}`),this.createWidget(t,n,s,r)),h[3]=="cmd"&&h[4]=="val"&&a&&a!=""){console.log(`changed ${t} type:${c.type} val:${a}`);let p=a.split("|");if(p[0]=="new"){if(p[1]!="program"){this[p[1]]=yield this.visTvprogram.getServerDataAsync(l,t,p[1]),this.createWidget(t,n,s,r);return}p[1]=="program"&&this.tvprogram[p[2]]&&this.visTvprogram.loadProgram(l,t,p[2],function(v,k,C,A,M,m){if(m!="error"&&m!="nodata"){this.tvprogram[M]=m,this.createWidget(v,k,C,A);return}}.bind(this,t,n,s,r,p[2]))}}})}},checkStyle:function(t,n){return n.split(";").reduce((s,r)=>r.split(":")[0].trim()==t?r.split(":")[1].trim():s,"")},realBackgroundColor:function(t){let n="rgba(0, 0, 0, 0)",s="transparent";if(!t)return n;let r=window.getComputedStyle(t).backgroundColor;return r===n||r===s?this.realBackgroundColor(t.parentElement):r},onclickBroadcast:function(t){return L(this,null,function*(){let n=t.currentTarget?t.currentTarget:t,s=n.dataset.eventid||0,r=n.dataset.widgetid||0,l=n.dataset.viewdate||0,c=n.dataset.instance||"",a=n.dataset.dp||"";if(s==0||r==0)return;let h=yield this.getServerBroadcastAsync(c,s,l),p=$(`#${r}broadcastdlg`).data(),v=new Date(h.startTime),k=new Date(h.endTime),C=h.content.category?this.categories.find(e=>e.id==h.content.category):null,A=h.channel?this.channels.find(e=>e.id==h.channel):null,M="";M+=A?`${A.name} `:"",M+=`${`0${v.getHours()}`.slice(-2)}:${`0${v.getMinutes()}`.slice(-2)}`,M+=" - ",M+=`${`0${k.getHours()}`.slice(-2)}:${`0${k.getMinutes()}`.slice(-2)}`;let m="";m+=h.content.country?`${h.content.country} `:"",m+=h.content.year?`${h.content.year} `:"",m+=C?`${C.title} `:"";let H="",o="";h.content.seasonNumber&&(H=h.content.seasonNumber,H=H<100?`S${`0${H}`.slice(-2)}`:`S${H}`),h.content.episodeNumber&&(o=h.content.episodeNumber,o=o<100?`E${`0${o}`.slice(-2)}`:`E${o}`),m+=H||o?`${H+o} `:"";let i=h.content.texts.Long.value?h.content.texts.Long.value:h.content.texts.VeryShort.value?h.content.texts.VeryShort.value:"",O=h.photo.url?`https://tvfueralle.de${h.photo.url}`:"https://tvfueralle.de/tv-logo-no-image.svg",x=this.getConfigFavorites(a).indexOf(h.title)>-1,w=$(`#${r}`).width()*p.dialogwidthpercent>$(`#${r}`).height()*p.dialogheightpercent?" tv-dlg-row":" tv-dlg-col",V="";V+=`  <div class="event-container${w}" data-eventid="${h.id}">`,V+=`    <div class="event-picture dialogcolumn${w}">`,V+=`    <img src="${O}">`,V+="    </div>",V+=`    <div class="event-data dialogcolumn${w}">`,V+='      <div class="buttoncontainer">',V+=`          <div class="record button" data-viewdate="${l}" data-eventid="${h.id}" data-instance="${c}" data-dp="${a}" onclick="return vis.binds.tvprogram.onclickRecord(this,event)"><svg width="100%" height="100%" ><use xlink:href="#record-icon"></use></svg></div>`,V+=`          <div class="copy button" data-widgetid="${r}" onclick="return vis.binds.tvprogram.onclickCopy(this,event)"><svg width="100%" height="100%" ><use xlink:href="#copy-icon"></use></svg></div>`,V+=`          <div class="star button ${x?"selected":""}" data-viewdate="${l}" data-eventid="${h.id}" data-instance="${c}" data-dp="${a}" onclick="return vis.binds.tvprogram.onclickFavorite(this,event)"><svg width="100%" height="100%" ><use xlink:href="#star-icon"></use></svg></div>`,v<new Date&&new Date<k&&(V+=`        <div class="channelselect button" data-instance="${c}" data-dp="${a}" data-channelid="${A.channelId}" onclick="vis.binds.tvprogram.onclickChannelSwitch(this,event)"><svg width="100%" height="100%" ><use xlink:href="#switch-icon"></use></svg></div>`),V+="      </div>",V+=`      <div style="padding: 0px 0px 5px;">${M}</div>`,V+=`      <div style="font-weight: bold;padding: 0px 0px 5px;">${h.title}</div>`,V+=`      <div style="padding: 0px 0px 5px;">${m}</div>`,V+=`      <div>${i}</div>`,V+="    </div>",V+="  </div>",V+="  </div>",$(`#${r}broadcastdlg`).html(V),$(`#${r}broadcastdlg`).dialog({resizable:!1,autoOpen:!1,modal:!0,position:{of:$(`#${r}`),within:$(`#${r}`)},width:$(`#${r}`).width()*p.dialogwidthpercent,height:$(`#${r}`).height()*p.dialogheightpercent,dialogClass:`no-titlebar ${r}`,zIndex:10003,stack:!1,collision:"none"}),this.copyStyles("font",$(`#${r}`).get(0),$(`#${r}broadcastdlg`).get(0)),this.copyStyles("color",$(`#${r}`).get(0),$(`#${r}broadcastdlg`).get(0)),this.copyStyles("background-color",$(`#${r}`).get(0),$(`#${r}broadcastdlg`).get(0)),$(`#${r}broadcastdlg`).dialog("open"),$(`#${r}broadcastdlg`).click(function(){$(`#${r}broadcastdlg`).dialog("close")})})},onclickRecord:function(t,n){return L(this,null,function*(){let s=t.dataset.instance||"",r=t.dataset.dp||"",l=t.dataset.eventid||0,c=t.dataset.viewdate||0;if(l==0||c==0)return;n.stopPropagation();let a=yield this.getServerBroadcastAsync(s,l,c),h=a.channel?this.channels.find(v=>v.id==a.channel):null,p={startTime:a.startTime,endTime:a.endTime,title:a.title,channel:a.channel,channelid:h.channelId,channelname:h.name,eventid:a.id};this.setValueAckAsync(s,`${r}.record`,JSON.stringify(p))})},onclickCopy:function(t,n){let s=t.dataset.widgetid||"",r=document.createElement("textarea");r.value=$(`#${s}broadcastdlg .event-data`).get(0).outerText,document.body.appendChild(r),r.focus(),r.select(),document.execCommand("copy"),document.body.removeChild(r),n.stopPropagation()},copyStyles:function(t,n,s){let r=window.getComputedStyle(n),l=window.getComputedStyle(s);for(let c=r.length;c--;)r[c].startsWith(t)&&r.getPropertyValue(r[c])!=l.getPropertyValue(r[c])&&s.style.setProperty(r[c],r.getPropertyValue(r[c]))},colorToRGBA:function(t,n=1){let s=document.createElement("canvas");s.height=1,s.width=1;let r=s.getContext("2d");r.fillStyle=t,r.fillRect(0,0,1,1);let l=r.getImageData(0,0,1,1).data;return`rgba(${l[0]},${l[1]},${l[2]},${n})`},onclickChannelSwitch:function(t,n){let s=t.dataset.channelid||"",r=t.dataset.dp||"",l=t.dataset.instance||"";this.setValueAckAsync(l,`${r}.selectchannel`,s),n.stopPropagation()},onclickFavorite:function(t,n){return L(this,null,function*(){let s=t.dataset.dp||"",r=t.dataset.instance||"",l=t.dataset.eventid||0,c=t.dataset.viewdate||0;if(n.stopPropagation(),l==0||c==0)return;let a=yield this.getServerBroadcastAsync(r,l,c),h=this.getConfigFavorites(s),p=h.indexOf(a.title);p>-1?(h.splice(p,1),$(t).hasClass("button")&&$(t).removeClass("selected")):(h.push(a.title),$(t).hasClass("button")&&$(t).addClass("selected")),this.setConfigFavorites(r,s,h)})},getConfig:function(t){let n,s=vis.states.attr(`${t}.config.val`);return typeof s!="undefined"&&s!=="null"&&s!==""?n=JSON.parse(s):n={},n},getConfigFavorites:function(t){let n,s=vis.states.attr(`${t}.favorites.val`);return typeof s!="undefined"&&s!=="null"&&s!==""?n=JSON.parse(s):n=[],n},setConfigFavorites:function(t,n,s){this.setValueAckAsync(t,`${n}.favorites`,JSON.stringify(s))},getConfigChannelfilter:function(t){let n,s=vis.states.attr(`${t}.channelfilter.val`);return typeof s!="undefined"&&s!=="null"&&s!==""?n=JSON.parse(s):n=[],n},setConfigChannelfilter:function(t,n,s){this.setValueAckAsync(t,`${n}.channelfilter`,JSON.stringify(s))},getConfigShow:function(t){let n,s=vis.states.attr(`${t}.show.val`);return typeof s!="undefined"&&s!=="null"&&s!==""?n=JSON.parse(s):n=1,n},setConfigShow:function(t,n,s){this.setValueAckAsync(t,`${n}.show`,JSON.stringify(s))},toggleShow:function(t,n){let s=this.getConfigShow(n);s==null&&(s=0),s=s==1?0:1,this.setConfigShow(t,n,s)},getServerBroadcast:function(t,n,s,r){console.log(`getServerBroadcast request ${n}.${s}`),vis.conn.sendTo(t,"getServerBroadcast",{eventid:n,viewdate:s},function(l){l!="error"&&l!="nodata"?console.log(`getServerBroadcast received ok ${t}.${s}.${n}`):console.log(`getServerBroadcast received ${l}`),r&&r(l)}.bind(this))},getServerBroadcastAsync:function(t,n,s){return L(this,null,function*(){return console.log(`getServerBroadcast request ${n}.${s}`),yield this.sendToAsync(t,"getServerBroadcast",{eventid:n,viewdate:s})})},events:{},serverdata:{},getServerData:function(t,n,s,r){let l=t+s;Object.prototype.hasOwnProperty.call(this.serverdata,l)&&r(this.serverdata[l]),Object.prototype.hasOwnProperty.call(this.events,l)||(this.events[l]=[]);let c=this.events[l];c.find(a=>a.key==n)||c.push({key:n,cb:r}),vis.conn.sendTo(t,"getServerData",s,a=>{if(a!="error"&&a!="nodata"?console.log(`getServerData received ${t}.${s} ${JSON.stringify(a).substring(0,100)}`):console.log(`getServerData received err ${a}`),this.serverdata[l]=a,!Object.prototype.hasOwnProperty.call(this.events,l))return;let h=this.events[l];for(let p=0;p<h.length;p++)h[p].cb(a);delete this.events[l]})},getServerDataAsync:function(t,n,s){return L(this,null,function*(){console.log(`getServerData ${s}`);let r=t+s;return Object.prototype.hasOwnProperty.call(this.events,r)||(this.events[r]=[]),yield this.sendToAsync(t,"getServerData",s)})},getServerTVProgram:function(t,n,s,r){let l=`${t}program.${s}`;if(Object.prototype.hasOwnProperty.call(this.serverdata,l)&&r(this.serverdata[l]),Object.prototype.hasOwnProperty.call(this.events,l)){this.events[l].find(c=>c.key==n)||this.events[l].push({key:n,cb:r});return}this.events[l]=[{key:n,cb:r}],vis.conn.sendTo(t,"getServerTVProgram",s,function(c){if(c!="error"&&c!="nodata"?console.log(`getServerTVProgram received ${t}.${s}nodata`):(console.log(`getServerTVProgram received ${t}.${s} ok`),this.serverdata[l]=c),!!Object.prototype.hasOwnProperty.call(this.events,l)){for(let a=0;a<this.events[l].length;a++)this.events[l][a].cb(c);delete this.events[l]}}.bind(this))},getServerTVProgramAsync:function(t,n,s){return L(this,null,function*(){return console.log(`getServerTVProgram ${s}`),yield this.sendToAsync(t,"getServerTVProgram",s)})},getFavoritesData:function(t,n=[],s){console.log(`getFavoritesData request ${t}.favorites`),vis.conn.sendTo(t,"getFavoritesData",n,r=>{r!="error"&&r!="nodata"?console.log(`getFavoritesData received ok ${r.length}`):console.log(`getFavoritesData received ${t}.favorites`),s&&s(r)})},getFavoritesDataAsync:function(s){return L(this,arguments,function*(t,n=[]){return console.log(`getFavoritesData request ${t}.favorites`),yield this.sendToAsync(t,"getFavoritesData",n)})},getServerInfo:function(t,n){console.log("getServerInfo request "),vis.conn.sendTo(t,"getServerInfo",{},s=>{console.log("getServerInfo received ok "),n&&n(s)})},getServerInfoAsync:function(t){return L(this,null,function*(){return console.log("getServerInfo request "),yield this.sendToAsync(t,"getServerInfo",{})})},getServerBroadcastNow:function(t,n,s){console.log("getServerBroadcastNow request "),vis.conn.sendTo(t,"getServerBroadcastNow",n,function(r){r!="error"&&r!="nodata"?console.log(`getServerBroadcastNow received ok ${r.length}`):console.log("getServerBroadcastNow received "),s&&s(r)}.bind(this))},getServerBroadcastNowAsync:function(t,n){return L(this,null,function*(){return console.log("getServerBroadcastNow request "),yield this.sendToAsync(t,"getServerBroadcastNow",n)})},getServerBroadcastRangeAsync:function(t,n,s,r){return L(this,null,function*(){return console.log("getServerBroadcastRange request "),yield this.sendToAsync(t,"getServerBroadcastRange",{channelfilter:n,startdate:s,enddate:r})})},getServerBroadcastDate:function(t,n,s,r){console.log("getServerBroadcastDate request "),vis.conn.sendTo(t,"getServerBroadcastDate",{channelfilter:n,date:s},function(l){l!="error"&&l!="nodata"?console.log(`getServerBroadcastDate received ok ${l.length}`):console.error(`getServerBroadcastDate received ${l}`),r&&r(l)}.bind(this))},getServerBroadcastDateAsync:function(t,n,s){return L(this,null,function*(){return console.log("getServerBroadcastDate request "),yield this.sendToAsync(t,"getServerBroadcastDate",{channelfilter:n,date:s})})},getServerBroadcastFind:function(t,n,s){console.log("getServerBroadcastFind request "),vis.conn.sendTo(t,"getServerBroadcastFind",n,function(r){r!="error"&&r!="nodata"?console.log(`getServerBroadcastFind received ok ${r.length}`):console.log("getServerBroadcastFind received ");let l=[];r.map(c=>{c.events.map(a=>l.push(a))}),r=l.sort((c,a)=>new Date(c.startTime)-new Date(a.startTime)),s&&s(r)}.bind(this))},getServerBroadcastFindAsync:function(t,n){return L(this,null,function*(){console.log("getServerBroadcastFind request ");let s=yield this.sendToAsync(t,"getServerBroadcastFind",n),r=[];return s.map(l=>{l.events.map(c=>r.push(c))}),s=r.sort((l,c)=>new Date(l.startTime)-new Date(c.startTime)),s})},setValueAck:function(t,n,s){console.log("setValueAck request "),vis.conn.sendTo(t,"setValueAck",{id:n,value:s},function(){}.bind(this))},setValueAckAsync:function(t,n,s){return L(this,null,function*(){return console.log("setValueAck request "),yield this.sendToAsync(t,"setValueAck",{id:n,value:s})})},sendToAsync:function(t,n,s){return L(this,null,function*(){return console.log(`sendToAsync ${n} ${s}`),new Promise((r,l)=>{try{vis.conn.sendTo(t,n,s,function(c){r(c)})}catch(c){l(c)}})})},loadServerInfosAsync:function(t){return L(this,null,function*(){return this.infos=[],yield this.getServerInfoAsync(t)})},loadCategories:function(t,n){return L(this,null,function*(){return console.log("loadCategories"),yield this.getServerDataAsync(t,n,"categories")})},loadChannels:function(t,n){return L(this,null,function*(){return console.log("loadChannels"),yield this.getServerDataAsync(t,n,"channels")})},loadGenres:function(t,n){return L(this,null,function*(){return console.log("loadGenres"),yield this.getServerDataAsync(t,n,"genres")})},loadProgram:function(t,n,s){return L(this,null,function*(){return console.log(`loadProgram ${s}`),yield this.getServerTVProgramAsync(t,n,s)})},calcDate:function(t){let n=new Date(t),s=n.getHours()+n.getMinutes()/60;return s>=0&&s<5&&n.setDate(n.getDate()-1),n},getDate:function(t,n){let s=new Date(t);return s.setDate(s.getDate()+n),`${s.getFullYear()}-${`0${s.getMonth()+1}`.slice(-2)}-${`0${s.getDate()}`.slice(-2)}`},compareDate:function(t,n){return t.getDate()==n.getDate()&&t.getMonth()==n.getMonth()&&t.getYear()==n.getYear()},getTvprogramId:function(t){let n=t.split(".");return n.length<2?"":(n=n.slice(0,3),n.join("."))},getInstance:function(t){let n=t.split(".");return n.length<2?"":(n=n.slice(0,2),n.join("."))},getInstanceInfo:function(t){console.log("getInstanceInfo");let n=t.trim().split(".");return n.length<2?[null,null]:[n.slice(0,2).join("."),n.slice(0,3).join(".")]},bindStates:function(t,n,s){console.log("bindStates");let r=$(t),l=r.data("bound");if(l)for(let c=0;c<l.length;c++)vis.states.unbind(l[c],s);r.data("bound",null),r.data("bindHandler",null),vis.conn.gettingStates=0,vis.conn.getStates(n,function(c,a){vis.conn.subscribe(n);for(let h=0;h<n.length;h++)n[h]=`${n[h]}.val`,vis.states.bind(n[h],s);vis.binds.tvprogram.updateStates(a),r.data("bound",n),r.data("bindHandler",s)}.bind({change_callback:s}))},updateStates:function(t){for(let n in t){if(!Object.prototype.hasOwnProperty.call(t,n))continue;let s=t[n];try{if(vis.editMode)vis.states[`${n}.val`]=s.val,vis.states[`${n}.ts`]=s.ts,vis.states[`${n}.ack`]=s.ack,vis.states[`${n}.lc`]=s.lc,s.q!==void 0&&s.q!==null&&(vis.states[`${n}.q`]=s.q);else{let r={};r[`${n}.val`]=s.val,r[`${n}.ts`]=s.ts,r[`${n}.ack`]=s.ack,r[`${n}.lc`]=s.lc,s.q!==void 0&&s.q!==null&&(r[`${n}.q`]=s.q),vis.states.attr(r)}}catch(r){console.error(`Error: can't create states object for ${n}(${r})`)}}}};vis.binds.tvprogram.showVersion();jQuery.fn.mydelay=function(t,n){return t=jQuery.fx&&jQuery.fx.speeds[t]||t,n=n||"fx",this.queue(n,function(s,r){let l=window.setTimeout(s,t);r.stop=function(){window.clearTimeout(l)}})}});rt();})();
//# sourceMappingURL=tvprogram-dist.js.map
