"use strict";(()=>{var W=(t,o)=>()=>(o||t((o={exports:{}}).exports,o),o.exports);var L=(t,o,n)=>new Promise((r,l)=>{var a=d=>{try{h(n.next(d))}catch(v){l(v)}},c=d=>{try{h(n.throw(d))}catch(v){l(v)}},h=d=>d.done?r(d.value):Promise.resolve(d.value).then(a,c);h((n=n.apply(t,o)).next())});var _=W(A=>{fetch("widgets/tvprogram/i18n/translations.json").then(t=>L(A,null,function*(){let o=yield t.json();$.extend(!0,systemDictionary,o)}));$.extend(!0,systemDictionary,{});vis.binds.tvprogram={version:"0.0.1",showVersion:function(){vis.binds.tvprogram.version&&(console.log("Version tvprogram: "+vis.binds.tvprogram.version),vis.binds.tvprogram.version=null)},pending:{},categories:null,channels:null,genres:null,tvprogram:[],infos:null,requests:[],search:{visTvprogram:null,bound:{},searchdata:[],searchresult:[],createWidget:function(t,o,n,r){let l=$("#"+t);if(!l.length)return setTimeout(function(){vis.binds.tvprogram.search.createWidget(t,o,n,r)},100);console.log("createWidget start"),this.visTvprogram=vis.binds.tvprogram;let a,c;if(!n.tvprogram_oid||(a=vis.binds.tvprogram.getTvprogramId(n.tvprogram_oid.trim()))==!1||!n.tvprogram_oid||(c=vis.binds.tvprogram.getInstance(n.tvprogram_oid.trim()))==!1)return;let h=this.visTvprogram.realBackgroundColor($("#"+t)[0]);this.visTvprogram.checkStyle("background-color",$("#"+t)[0].style.cssText)==""&&$("#"+t).css("background-color",h);let d=parseInt(n.tvprogram_maxresults)||10,v=parseInt(n.tvprogram_heightRow)||35,m=parseInt(n.tvprogram_broadcastfontpercent)||75,g=n.tvprogram_highlightcolor||"yellow",x=n.tvprogram_showpictures||!1,f=n.tvprogram_dialogwidthpercent/100||.9,u=n.tvprogram_dialogheightpercent/100||.9;if(this.searchresult[a]||(this.searchresult[a]={}),this.searchresult[a][t]||(this.searchresult[a][t]=[]),this.searchdata[a]||(this.searchdata[a]={}),this.searchdata[a][t]||(this.searchdata[a][t]={datefrom:new Date().toISOString().split("T")[0],categoryfilter:"",textfilter:"",maxresults:d||10}),this.bound[a]||(this.bound[a]={}),this.bound[a][t]||(this.bound[a][t]=!1),a&&!this.bound[a][t]&&(this.bound[a][t]=!0,vis.binds.tvprogram.bindStates(l,[a+".config",a+".favorites",a+".channelfilter"],this.onChange.bind(this,t,o,n,r,a))),this.infos==null&&(this.infos={},this.visTvprogram.getServerInfo(c,p=>{this.infos=p,this.createWidget(t,o,n,r)})),this.visTvprogram.loadServerInfos(c,()=>this.createWidget(t,o,n,r)),this.visTvprogram.loadCategories(c,t,()=>this.createWidget(t,o,n,r)),this.visTvprogram.loadChannels(c,t,()=>this.createWidget(t,o,n,r)),this.visTvprogram.infos==null||!Object.prototype.hasOwnProperty.call(this.infos,"tvprogram")||this.visTvprogram.categories.length==0||this.visTvprogram.categories[0]==="request"||this.visTvprogram.channels.length==0||this.visTvprogram.channels[0]==="request")return;let y=this.visTvprogram.categories.map(p=>'<option value="'+p.id+'" '+(this.searchdata[a][t].categoryfilter==p.id?" selected":"")+">"+p.title+"</option>");y='<option value="" '+(this.searchdata[a][t].categoryfilter==""?" selected":"")+"></option>"+y,$("#"+t+"broadcastdlg").data({dialogwidthpercent:f,dialogheightpercent:u});let s="";s+=`<style> 
`,s+="#"+t+` * {
`,s+=`   box-sizing: border-box; 
`,s+=`} 
`,s+="#"+t+` .tv-search {
`,s+=`   width: 100%; 
`,s+=`   height: 100%; 
`,s+=`   white-space:nowrap; 
`,s+=`   display:flex; 
`,s+=`   flex-direction: column; 
`,s+=`} 
`,s+="#"+t+` .tv-form {
`,s+=`   padding: 5px 0px; 
`,s+=`} 
`,s+="#"+t+` .tv-result {
`,s+=`   overflow: hidden; 
`,s+=`   overflow-y: auto; 
`,s+=`} 
`,s+="#"+t+` .tv-row {
`,s+=`   margin: 0px; 
`,s+=`   padding: 0px; 
`,s+=`   width: 100%; 
`,s+=`} 
`,s+="#"+t+` .tv-search .tv-row:nth-child(odd) {
`,s+=`   background-color: rgba(128,127,127,.65); 
`,s+=`   padding: 0px; 
`,s+=`} 
`,s+="#"+t+` .tv-search .tv-row:nth-child(even) {
`,s+=`   background-color: rgba(128,127,127,.55); 
`,s+=`   padding: 0px; 
`,s+=`} 
`,s+="#"+t+` .tv-item {
`,s+=`   display: inline-block; 
`,s+=`   vertical-align: middle; 
`,s+=`   border: solid #80808033; 
`,s+=`   border-width:1px 0px 0px 1px; 
`,s+=`} 
`,s+="#"+t+` .channel {
`,s+="   width: "+v+`px; 
`,s+="   height: "+v+`px; 
`,s+=`   padding: 1px; 
`,s+="   background-color: "+h+`; 
`,s+=`} 
`,s+="#"+t+` .broadcast {
`,s+="   height: "+v+`px; 
`,s+=`   padding: 3px; 
`,s+="   font-size: "+m+`%; 
`,s+=`   overflow: hidden; 
`,s+=`   width: 100%; 
`,s+=`} 
`,s+="#"+t+` .broadcastelement {
`,s+=`   width: 100%; 
`,s+=`   height: 100%; 
`,s+=`   display: table-cell; 
`,s+=`} 
`,s+="#"+t+` .broadcastelement .star  {
`,s+=`   display: inline-block; 
`,s+=`   margin: 0px 2px; 
`,s+=`} 
`,s+="#"+t+` .broadcastelement .star svg {
`,s+=`   height: 1em; 
`,s+=`   width: 1em; 
`,s+=`   position: relative; 
`,s+=`   top: .125em; 
`,s+=`} 
`,s+="#"+t+` .broadcastelement.selected .star svg path {
`,s+="   color: "+g+`; 
`,s+=`} 
`,s+="#"+t+` .broadcastelement.selected {
`,s+="   color: "+g+`; 
`,s+=`} 
`,s+="#"+t+` .broadcastimage {
`,s+="   height: "+(v-7)+`px; 
`,s+=`   padding-right: 3px; 
`,s+=`   float: left; 
`,s+=`} 
`,s+="."+t+`.no-titlebar .ui-dialog-titlebar {
`,s+=`   display:none; 
`,s+=`} 
`,s+="#"+t+`broadcastdlg  {
`,s+=`   z-index:12; 
`,s+=`} 
`,s+="#"+t+`broadcastdlg .event-container.tv-dlg-row {
`,s+=`   height:100%; 
`,s+=`   display:flex; 
`,s+=`   flex-direction:row; 
`,s+=`   overflow:hidden; 
`,s+=`} 
`,s+="#"+t+`broadcastdlg .event-container.tv-dlg-col {
`,s+=`   height:100%; 
`,s+=`   display:flex; 
`,s+=`   flex-direction:column; 
`,s+=`   overflow:hidden; 
`,s+=`   font-size:75%; 
`,s+=`} 
`,s+="#"+t+`broadcastdlg .event-picture.tv-dlg-row {
`,s+=`   width:50%; 
`,s+=`} 
`,s+="#"+t+`broadcastdlg .event-picture.tv-dlg-col {
`,s+=`   height:30%; 
`,s+=`} 
`,s+="#"+t+`broadcastdlg .event-data {
`,s+=`   overflow-y:auto; 
`,s+=`} 
`,s+="#"+t+`broadcastdlg .event-picture img {
`,s+=`   width:auto; 
`,s+=`   height:auto; 
`,s+=`   max-width:100%; 
`,s+=`   max-height:100%; 
`,s+=`   display:block; 
`,s+=`   margin:auto; 
`,s+=`} 
`,s+="#"+t+`broadcastdlg .event-picture img {
`,s+=`   width:auto; 
`,s+=`   height:auto; 
`,s+=`   max-width:100%; 
`,s+=`   max-height:100%; 
`,s+=`   display:block; 
`,s+=`   margin:auto; 
`,s+=`} 
`,s+="#"+t+`broadcastdlg .dialogcolumn.tv-dlg-row {
`,s+=`   flex:1; 
`,s+=`   padding:5px; 
`,s+=`} 
`,s+="#"+t+`broadcastdlg .dialogcolumn.tv-dlg-col {
`,s+=`   padding:5px; 
`,s+=`} 
`,s+="#"+t+`broadcastdlg .button {
`,s+=`   display:inline-block; 
`,s+=`   width: 35px; 
`,s+=`   height: 35px; 
`,s+=`   vertical-align: middle; 
`,s+=`   position: relative; 
`,s+=`   float: right; 
`,s+=`} 
`,s+="#"+t+`broadcastdlg .star.selected svg  {
`,s+=`   filter: drop-shadow( 2px 2px 2px rgba(0, 0, 0, .7))
`,s+=`} 
`,s+="#"+t+" .broadcastelement.selected .star svg path, #"+t+`broadcastdlg .star.selected {
`,s+="   color: "+g+`; 
`,s+=`} 
`,s+=`</style> 
`,s+='  <div class="svgcontainer">',s+='<svg style="display:none;"><symbol id="star-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" /></symbol></svg>',s+='<svg style="display:none;"><symbol id="copy-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M19,21H8V7H19M19,5H8A2,2 0 0,0 6,7V21A2,2 0 0,0 8,23H19A2,2 0 0,0 21,21V7A2,2 0 0,0 19,5M16,1H4A2,2 0 0,0 2,3V17H4V3H16V1Z" /></symbol></svg>',s+='<svg style="display:none;"><symbol id="switch-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M21,3H3C1.89,3 1,3.89 1,5V17A2,2 0 0,0 3,19H8V21H16V19H21A2,2 0 0,0 23,17V5C23,3.89 22.1,3 21,3M21,17H3V5H21M16,11L9,15V7" /></symbol></svg>',s+='<svg style="display:none;"><symbol id="record-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12.5,5A7.5,7.5 0 0,0 5,12.5A7.5,7.5 0 0,0 12.5,20A7.5,7.5 0 0,0 20,12.5A7.5,7.5 0 0,0 12.5,5M7,10H9A1,1 0 0,1 10,11V12C10,12.5 9.62,12.9 9.14,12.97L10.31,15H9.15L8,13V15H7M12,10H14V11H12V12H14V13H12V14H14V15H12A1,1 0 0,1 11,14V11A1,1 0 0,1 12,10M16,10H18V11H16V14H18V15H16A1,1 0 0,1 15,14V11A1,1 0 0,1 16,10M8,11V12H9V11" /></symbol></svg>',s+="  </div>",s+='  <form data-instance="'+c+'" data-dp="'+a+'" data-widgetid="'+t+'" data-maxresults="'+d+'" >',s+='    <label for="tvsearch">Search:',s+='      <input name="tvsearch" type="text" id="tvsearch" value="'+this.searchdata[a][t].textfilter+'" placeholder="Search">',s+="    </label>",s+='    <label for="tvfrom">From:',s+='      <input name="tvfrom" autocomplete="off"  type="date" id="tvfrom" min="'+this.infos.tvprogram[0]+'" max="'+this.infos.tvprogram[this.infos.tvprogram.length-1]+'" value="'+this.searchdata[a][t].datefrom+'">',s+="    </label>",s+='    <label for="tvcategory">Category:',s+='      <select name="tvcategory" id="tvcategory" >',s+=y,s+="      </select>",s+="    </label>",s+="  <button>Search</Search>",s+="  </form>",$("#"+t+" .tv-form").html(s),$("#"+t+" .tv-form form").submit(this.onSubmitSearch.bind(this,t,o,n,r));let i,k;s="";let C=this.visTvprogram.getConfigFavorites(a);this.searchresult[a][t].map((p,b)=>{if(b+1>d)return;let H=this.visTvprogram.channels.find(S=>S.id==p.channel);i=C.indexOf(p.title)>-1,k=p.airDate,s+='    <ul class="tv-row">',s+='       <li class="tv-item channel">',s+='          <img width="100%" height="100%" data-channelid="'+H.channelId+'" data-dp="'+a+'" data-instance="'+c+'" src="https://tvfueralle.de/channel-logos/'+H.channelId+'.png" alt="" class="channel-logo"  onclick="vis.binds.tvprogram.onclickChannelSwitch(this,event)">',s+="       </li>",s+='       <li class="tv-item broadcast">',s+='             <div class="broadcastelement '+(i?"selected":"")+'" data-widgetid="'+t+'" data-eventid="'+p.id+'" data-viewdate="'+k+'" data-instance="'+c+'" data-dp="'+a+'" data-view="" >',p.photo.url&&x&&(s+='<div><img class="broadcastimage" src="https://tvfueralle.de'+p.photo.url+'"></div>'),s+='                 <div class="broadcasttitle">',s+="                     "+p.title,s+='                     <div class="star" data-viewdate="'+k+'" data-eventid="'+p.id+'" data-instance="'+c+'" data-dp="'+a+'" onclick="return vis.binds.tvprogram.onclickFavorite(this,event)"><svg width="100%" height="100%" ><use xlink:href="#star-icon"></use></svg></div>',s+="                 </div>";let e=new Date(p.startTime),V=new Date(p.endTime);s+='                 <div class="broadcasttime">',s+=("0"+e.getDate()).slice(-2)+"."+("0"+parseInt(e.getMonth()+1)).slice(-2)+"."+("0"+e.getFullYear()).slice(-4)+" ",s+=("0"+e.getHours()).slice(-2)+":"+("0"+e.getMinutes()).slice(-2),s+=" - ",s+=("0"+V.getHours()).slice(-2)+":"+("0"+V.getMinutes()).slice(-2),s+="                 </div>",s+="             </div>",s+="       </li>",s+="    </ul>"}),$("#"+t+" .tv-result").html(s),$("#"+t+" .tv-result .broadcastelement").click(vis.binds.tvprogram.onclickBroadcast.bind(this.visTvprogram))},onSubmitSearch:function(t,o,n,r,l){let a=l.target,c=a.dataset.instance||"",h=a.dataset.dp||"";l.preventDefault();let d=$(a).find('[name="tvsearch"]').val(),v=$(a).find('[name="tvcategory"]').val(),m=$(a).find('[name="tvfrom"]').val();if(!this.parseDatestring(m))return!1;let g=this.visTvprogram.getConfigChannelfilter(h);g.length==0&&(g=this.visTvprogram.channels.reduce((s,i,k)=>(k<4&&s.push(i.id),s),[])),this.searchdata[h]||(this.searchdata[h]={}),this.searchdata[h][t]=Object.assign(this.searchdata[h][t],{datefrom:m,categoryfilter:[v],textfilter:d});let x=new Date,f=this.parseDatestring(m);x.getDate()==f.getDate()&&x.getMonth()==f.getMonth()&&x.getFullYear()==f.getFullYear()?(f.setHours(x.getHours()),f.setMinutes(x.getMinutes()),f.setSeconds(x.getSeconds())):(f.setHours(0),f.setMinutes(0),f.setSeconds(0));let u=new Date(x);u.setDate(u.getDate()+10);let y={channelfilter:g,datefrom:f,datetill:u,categoryfilter:v==""?[]:[parseInt(v)],textfilter:d,maxresults:this.searchdata[h][t].maxresults};return d==""&&v==""||this.visTvprogram.getServerBroadcastFind(c,y,function(s){this.searchresult[h][t]=s,this.createWidget(t,o,n,r)}.bind(this)),!1},parseDatestring:function(t){let o=t.split(/\D/),n=new Date(o[0],--o[1],o[2]);return n&&n.getMonth()==o[1]?n:!1},onChange:function(t,o,n,r,l,a,c){let h=a.type.split(".");(h[3]=="config"||h[3]=="favorites"||h[3]=="channelfilter"||h[3]=="show")&&h[4]=="val"&&(console.log("changed "+t+" type:"+a.type+" val:"+c),this.createWidget(t,o,n,r))}},control:{visTvprogram:null,bound:{},programdata:{},favorites:void 0,timer:{},createWidget:function(t,o,n,r){let l=$("#"+t);if(!l.length)return setTimeout(function(){vis.binds.tvprogram.control.createWidget(t,o,n,r)},100);console.log("createWidget control start"),this.visTvprogram=vis.binds.tvprogram;let a,c;if(!n.tvprogram_oid||(a=vis.binds.tvprogram.getTvprogramId(n.tvprogram_oid.trim()))==!1||!n.tvprogram_oid||(c=vis.binds.tvprogram.getInstance(n.tvprogram_oid.trim()))==!1||(this.visTvprogram.loadCategories(c,t,()=>this.createWidget(t,o,n,r)),this.visTvprogram.loadChannels(c,t,()=>this.createWidget(t,o,n,r)),this.visTvprogram.channels.length==0||this.visTvprogram.channels[0]==="request"||this.visTvprogram.categories.length==0||this.visTvprogram.categories[0]==="request"))return;let h=this.visTvprogram.realBackgroundColor($("#"+t)[0]);this.visTvprogram.checkStyle("background-color",$("#"+t)[0].style.cssText)==""&&$("#"+t).css("background-color",h);let d=this.visTvprogram.getConfigChannelfilter(a);d.length==0&&(d=this.visTvprogram.channels.reduce((p,b,H)=>(H<4&&p.push(b.id),p),[]));let v=n.tvprogram_time||"";if(this.programdata[a]||(this.programdata[a]={}),this.programdata[a][t]||(this.programdata[a][t]=[],v==""?(Object.keys(this.programdata[a][t]).length==0||this.programdata[a][t].some(p=>new Date(p.endTime)<=new Date))&&this.visTvprogram.getServerBroadcastNow(c,d,function(p,b,H,e,V){this.programdata[a][p]=V,this.programdata[a][p].length>0&&this.createWidget(p,b,H,e)}.bind(this,t,o,n,r)):(Object.keys(this.programdata[a][t]).length==0||this.programdata[a][t].some(p=>new Date(p.endTime)<=new Date))&&this.visTvprogram.getServerBroadcastDate(c,d,this.parseTime(v),function(p,b,H,e,V){this.programdata[a][p]=V,this.programdata[a][p].length>0&&this.createWidget(p,b,H,e)}.bind(this,t,o,n,r))),this.programdata[a][t]=="error")return;this.bound[a]||(this.bound[a]={}),this.bound[a][t]||(this.bound[a][t]=!1),a&&!this.bound[a][t]&&(this.bound[a][t]=!0,vis.binds.tvprogram.bindStates(l,[a+".config",a+".favorites",a+".channelfilter"],this.onChange.bind(this,t,o,n,r,a)));let m=this.visTvprogram.getDate(this.visTvprogram.calcDate(this.parseTime(v)),0),g=parseInt(n.tvprogram_heightRow)||35,x=parseInt(n.tvprogram_broadcastfontpercent)||75,f=n.tvprogram_highlightcolor||"yellow",u=n.tvprogram_showpictures||!1,y=n.tvprogram_dialogwidthpercent/100||.9,s=n.tvprogram_dialogheightpercent/100||.9;$("#"+t+"broadcastdlg").data({dialogwidthpercent:y,dialogheightpercent:s});let i="";i+=`<style> 
`,i+="#"+t+` * {
`,i+=`   box-sizing: border-box; 
`,i+=`} 
`,i+="#"+t+` .tv-control {
`,i+=`   width: 100%; 
`,i+=`   height: 100%; 
`,i+=`   white-space:nowrap; 
`,i+=`   display:flex; 
`,i+=`   flex-direction: column; 
`,i+=`   overflow: hidden; 
`,i+=`   overflow-y: auto; 
`,i+=`} 
`,i+="#"+t+` .tv-row {
`,i+=`   margin: 0px; 
`,i+=`   padding: 0px; 
`,i+=`   width: 100%; 
`,i+=`} 
`,i+="#"+t+` .tv-control .tv-row:nth-child(odd) {
`,i+=`   background-color: rgba(128,127,127,.65); 
`,i+=`   padding: 0px; 
`,i+=`} 
`,i+="#"+t+` .tv-control .tv-row:nth-child(even) {
`,i+=`   background-color: rgba(128,127,127,.55); 
`,i+=`   padding: 0px; 
`,i+=`} 
`,i+="#"+t+` .tv-item {
`,i+=`   display: inline-block; 
`,i+=`   vertical-align: middle; 
`,i+=`   border: solid #80808033; 
`,i+=`   border-width:1px 0px 0px 1px; 
`,i+=`} 
`,i+="#"+t+` .channel {
`,i+="   width: "+g+`px; 
`,i+="   height: "+g+`px; 
`,i+=`   padding: 1px; 
`,i+="   background-color: "+h+`; 
`,i+=`} 
`,i+="#"+t+` .broadcast {
`,i+="   height: "+g+`px; 
`,i+=`   padding: 3px; 
`,i+="   font-size: "+x+`%; 
`,i+=`   overflow: hidden; 
`,i+=`   width: 100%; 
`,i+=`} 
`,i+="#"+t+` .broadcastelement {
`,i+=`   width: 100%; 
`,i+=`   height: 100%; 
`,i+=`   display: table-cell; 
`,i+=`} 
`,i+="#"+t+` .broadcastelement .star  {
`,i+=`   display: inline-block; 
`,i+=`   margin: 0px 2px; 
`,i+=`} 
`,i+="#"+t+` .broadcastelement .star svg {
`,i+=`   height: 1em; 
`,i+=`   width: 1em; 
`,i+=`   position: relative; 
`,i+=`   top: .125em; 
`,i+=`} 
`,i+="#"+t+` .broadcastelement.selected .star svg path {
`,i+="   color: "+f+`; 
`,i+=`} 
`,i+="#"+t+` .broadcastelement.selected {
`,i+="   color: "+f+`; 
`,i+=`} 
`,i+="#"+t+` .broadcastimage {
`,i+="   height: "+(g-7)+`px; 
`,i+=`   padding-right: 3px; 
`,i+=`   float: left; 
`,i+=`} 
`,i+="."+t+`.no-titlebar .ui-dialog-titlebar {
`,i+=`   display:none; 
`,i+=`} 
`,i+="#"+t+`broadcastdlg  {
`,i+=`   z-index:12; 
`,i+=`} 
`,i+="#"+t+`broadcastdlg .event-container.tv-dlg-row {
`,i+=`   height:100%; 
`,i+=`   display:flex; 
`,i+=`   flex-direction:row; 
`,i+=`   overflow:hidden; 
`,i+=`} 
`,i+="#"+t+`broadcastdlg .event-container.tv-dlg-col {
`,i+=`   height:100%; 
`,i+=`   display:flex; 
`,i+=`   flex-direction:column; 
`,i+=`   overflow:hidden; 
`,i+=`   font-size:75%; 
`,i+=`} 
`,i+="#"+t+`broadcastdlg .event-picture.tv-dlg-row {
`,i+=`   width:50%; 
`,i+=`} 
`,i+="#"+t+`broadcastdlg .event-picture.tv-dlg-col {
`,i+=`   height:30%; 
`,i+=`} 
`,i+="#"+t+`broadcastdlg .event-data {
`,i+=`   overflow-y:auto; 
`,i+=`} 
`,i+="#"+t+`broadcastdlg .event-picture img {
`,i+=`   width:auto; 
`,i+=`   height:auto; 
`,i+=`   max-width:100%; 
`,i+=`   max-height:100%; 
`,i+=`   display:block; 
`,i+=`   margin:auto; 
`,i+=`} 
`,i+="#"+t+`broadcastdlg .event-picture img {
`,i+=`   width:auto; 
`,i+=`   height:auto; 
`,i+=`   max-width:100%; 
`,i+=`   max-height:100%; 
`,i+=`   display:block; 
`,i+=`   margin:auto; 
`,i+=`} 
`,i+="#"+t+`broadcastdlg .dialogcolumn.tv-dlg-row {
`,i+=`   flex:1; 
`,i+=`   padding:5px; 
`,i+=`} 
`,i+="#"+t+`broadcastdlg .dialogcolumn.tv-dlg-col {
`,i+=`   padding:5px; 
`,i+=`} 
`,i+="#"+t+`broadcastdlg .button {
`,i+=`   display:inline-block; 
`,i+=`   width: 35px; 
`,i+=`   height: 35px; 
`,i+=`   vertical-align: middle; 
`,i+=`   position: relative; 
`,i+=`   float: right; 
`,i+=`} 
`,i+="#"+t+`broadcastdlg .star.selected svg  {
`,i+=`   filter: drop-shadow( 2px 2px 2px rgba(0, 0, 0, .7))
`,i+=`} 
`,i+="#"+t+" .broadcastelement.selected .star svg path, #"+t+`broadcastdlg .star.selected {
`,i+="   color: "+f+`; 
`,i+=`} 
`,i+=`</style> 
`,i+='  <div class="svgcontainer">',i+='<svg style="display:none;"><symbol id="star-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" /></symbol></svg>',i+='<svg style="display:none;"><symbol id="copy-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M19,21H8V7H19M19,5H8A2,2 0 0,0 6,7V21A2,2 0 0,0 8,23H19A2,2 0 0,0 21,21V7A2,2 0 0,0 19,5M16,1H4A2,2 0 0,0 2,3V17H4V3H16V1Z" /></symbol></svg>',i+='<svg style="display:none;"><symbol id="switch-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M21,3H3C1.89,3 1,3.89 1,5V17A2,2 0 0,0 3,19H8V21H16V19H21A2,2 0 0,0 23,17V5C23,3.89 22.1,3 21,3M21,17H3V5H21M16,11L9,15V7" /></symbol></svg>',i+='<svg style="display:none;"><symbol id="record-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12.5,5A7.5,7.5 0 0,0 5,12.5A7.5,7.5 0 0,0 12.5,20A7.5,7.5 0 0,0 20,12.5A7.5,7.5 0 0,0 12.5,5M7,10H9A1,1 0 0,1 10,11V12C10,12.5 9.62,12.9 9.14,12.97L10.31,15H9.15L8,13V15H7M12,10H14V11H12V12H14V13H12V14H14V15H12A1,1 0 0,1 11,14V11A1,1 0 0,1 12,10M16,10H18V11H16V14H18V15H16A1,1 0 0,1 15,14V11A1,1 0 0,1 16,10M8,11V12H9V11" /></symbol></svg>',i+="  </div>";let k,C=this.visTvprogram.getConfigFavorites(a);this.programdata[a][t].map(p=>{p.events.map(b=>{let H=this.visTvprogram.channels.find(S=>S.id==b.channel);k=C.indexOf(b.title)>-1,i+='    <ul class="tv-row">',i+='       <li class="tv-item channel">',i+='          <img width="100%" height="100%" data-channelid="'+H.channelId+'" data-dp="'+a+'" src="https://tvfueralle.de/channel-logos/'+H.channelId+'.png" alt="" class="channel-logo"  onclick="vis.binds.tvprogram.onclickChannelSwitch(this,event)">',i+="       </li>",i+='       <li class="tv-item broadcast">',i+='             <div class="broadcastelement '+(k?"selected":"")+'" data-widgetid="'+t+'" data-eventid="'+b.id+'" data-viewdate="'+m+'" data-instance="'+c+'" data-dp="'+a+'" data-view="'+o+'" onclick="vis.binds.tvprogram.onclickBroadcast(this)">',b.photo.url&&u&&(i+='<div><img class="broadcastimage" src="https://tvfueralle.de'+b.photo.url+'"></div>'),i+='                 <div class="broadcasttitle">',i+="                     "+b.title,i+='                     <div class="star" data-viewdate="'+m+'" data-eventid="'+b.id+'" data-instance="'+c+'" data-dp="'+a+'" onclick="return vis.binds.tvprogram.onclickFavorite(this,event)"><svg width="100%" height="100%" ><use xlink:href="#star-icon"></use></svg></div>',i+="                 </div>";let e=new Date(b.startTime),V=new Date(b.endTime);i+='                 <div class="broadcasttime">',i+=("0"+e.getHours()).slice(-2)+":"+("0"+e.getMinutes()).slice(-2),i+=" - ",i+=("0"+V.getHours()).slice(-2)+":"+("0"+V.getMinutes()).slice(-2),i+="                 </div>",i+="             </div>",i+="       </li>",i+="    </ul>"})}),$("#"+t+" .tv-control").html(i),this.timer[t]?(clearInterval(this.timer[t]),this.timer[t]=setInterval(()=>{this.programdata[a][t].reduce((b,H)=>(b.push(H.events[0]),b),[]).some(b=>new Date(b.endTime)<=new Date)&&(this.programdata[a][t]=[],vis.binds.tvprogram.control.createWidget(t,o,n,r))},1e3*60)):this.timer[t]=setInterval(()=>{this.programdata[a][t].reduce((b,H)=>(b.push(H.events[0]),b),[]).some(b=>new Date(b.endTime)<=new Date)&&(this.programdata[a][t]=[],vis.binds.tvprogram.control.createWidget(t,o,n,r))},1e3*60)},parseTime:function(t){let o=new Date(t);if(o instanceof Date&&!isNaN(o))return o;if(t=="")return new Date;let n=t.split("/"),r=120;n.length>1&&parseInt(n[1].trim())>0&&(r=parseInt(n[1].trim())),n=n[0].split(":");let l=new Date;l.setHours(parseInt(n[0])),l.setMinutes(parseInt(n[1])),l.setSeconds(0);let a=new Date(l);return l.setMinutes(l.getMinutes()+r),new Date<l?a:a.setDate(a.getDate()+1)},onChange:function(t,o,n,r,l,a,c){let h=a.type.split(".");(h[3]=="config"||h[3]=="favorites"||h[3]=="channelfilter"||h[3]=="show")&&h[4]=="val"&&(console.log("changed "+t+" type:"+a.type+" val:"+c),this.tvprogram=[],this.createWidget(t,o,n,r))}},favorites:{visTvprogram:null,pending:{},bound:{},favorites:void 0,timer:{},createWidget:function(t,o,n,r){let l=$("#"+t);if(!l.length)return setTimeout(function(){vis.binds.tvprogram.favorites.createWidget(t,o,n,r)},100);console.log("createWidget start"),this.visTvprogram=vis.binds.tvprogram;let a=n.tvprogram_showweekday||!1,c=n.tvprogram_maxfavorites||10,h=n.tvprogram_highlightcolor||"yellow",d=n.tvprogram_channelname||!1,v,m,g={weekday:"short"},x={month:"2-digit",day:"2-digit"},f={hour:"2-digit",minute:"2-digit"};if(!n.tvprogram_oid||(v=vis.binds.tvprogram.getTvprogramId(n.tvprogram_oid.trim()))==!1||!n.tvprogram_oid||(m=vis.binds.tvprogram.getInstance(n.tvprogram_oid.trim()))==!1)return;let u=this.visTvprogram.realBackgroundColor($("#"+t)[0]);this.visTvprogram.checkStyle("background-color",$("#"+t)[0].style.cssText)==""&&$("#"+t).css("background-color",u),this.bound[v]||(this.bound[v]={}),this.bound[v][t]||(this.bound[v][t]=!1),v&&!this.bound[v][t]&&(this.bound[v][t]=!0,vis.binds.tvprogram.bindStates(l,[v+".config",v+".favorites"],this.onChange.bind(this,t,o,n,r,v)));let y=this.visTvprogram.getConfigFavorites(v);if((!this.favorites||!this.favorites[v]&&y)&&this.visTvprogram.getFavoritesData(m,y,function(i,k,C,p,b,H){this.favorites||(this.favorites=[]),this.favorites[b]=H,this.createWidget(i,k,C,p)}.bind(this,t,o,n,r,v)),!this.favorites||!this.favorites[v])return;let s="";s+=`<style> 
`,s+="#"+t+` .tv-fav {
`,s+=`   width: 100%;
`,s+=`} 
`,s+="#"+t+` .tv-fav td{
`,s+=`   white-space: nowrap;
`,s+=`} 
`,s+="#"+t+` .tv-left {
`,s+=`   text-align: left;
`,s+=`   width: 1%;
`,s+=`} 
`,s+="#"+t+` .tv-full {
`,s+=`   width: 50%;
`,s+=`} 
`,s+="#"+t+` .tv-fav .star {
`,s+=`   width: 1em;
`,s+=`   height: 1em;
`,s+="   color: "+h+`; 
`,s+=`} 
`,s+="#"+t+` .tv-center {
`,s+=`   text-align: center;
`,s+=`   width: 1%;
`,s+=`} 
`,s+="#"+t+` .tv-icon {
`,s+=`   height: 1em; 
`,s+=`   width: 1em; 
`,s+=`} 
`,s+=`</style> 
`,s+='  <div class="svgcontainer">',s+='<svg style="display:none;"><symbol id="star-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" /></symbol></svg>',s+="  </div>",s+='<table class="tv-fav">',this.favorites[v]=this.favorites[v].filter(i=>new Date(i.endTime)>=new Date),this.favorites[v].forEach(function(i,k){let C=new Date,p=new Date(i.startTime),b=new Date(i.endTime);k<c&&(vis.binds.tvprogram.compareDate(C,p)?s+='        <tr class="tv-today">':s+="        <tr>",s+='<td class="tv-left" data-viewdate="'+i.viewdate+'" data-eventid="'+i.id+'" data-instance="'+m+'" data-dp="'+v+'" onclick="return vis.binds.tvprogram.onclickFavorite(this,event)"><div class="star"><svg width="100%" height="100%" ><use xlink:href="#star-icon"></use></svg></div></td>',a&&(s+='           <td class="tv-left">'+p.toLocaleString(vis.language,g)+"</td>"),s+='           <td class="tv-left">'+p.toLocaleString(vis.language,x)+"</td>",s+='           <td class="tv-left">'+p.toLocaleString(vis.language,f)+"</td>",s+='           <td class="tv-left">-</td>',s+='           <td class="tv-left">'+b.toLocaleString(vis.language,f)+"</td>",d?s+='           <td class="tv-left">'+i.channelname+"</td>":(s+='           <td class="tv-center tv-tdicon">',s+='              <img width="100%" height="100%" src="https://tvfueralle.de/channel-logos/'+i.channelid+'.png" alt="" class="tv-icon">',s+="           </td>"),s+='           <td class="tv-full">'+i.title+"</td>",s+="        </tr>")}),s+="</table>            ",$("#"+t).html(s),this.timer[t]?(clearInterval(this.timer[t]),this.timer[t]=setInterval(vis.binds.tvprogram.favorites.createWidget.bind(this,t,o,n,r),1e3*60)):this.timer[t]=setInterval(vis.binds.tvprogram.favorites.createWidget.bind(this,t,o,n,r),1e3*60)},onChange:function(t,o,n,r,l,a,c){let h=a.type.split(".");(h[3]=="config"||h[3]=="favorites"||h[3]=="channelfilter"||h[3]=="show")&&h[4]=="val"&&(console.log("changed "+t+" type:"+a.type+" val:"+c),this.favorites=[],this.createWidget(t,o,n,r))}},time1:{visTvprogram:null,tvprogram:{},bound:{},timer:{},pending:{},measures:{},scroll:{},today:{},viewday:{},olddata:{},createWidget:function(t,o,n,r){let l=$("#"+t);if(!l.length)return setTimeout(function(){vis.binds.tvprogram.time1.createWidget(t,o,n,r)},100);console.log("createWidget start "+t);let a,c;if(this.visTvprogram=vis.binds.tvprogram,!n.tvprogram_oid||(a=vis.binds.tvprogram.getTvprogramId(n.tvprogram_oid.trim()))==!1||!n.tvprogram_oid||(c=vis.binds.tvprogram.getInstance(n.tvprogram_oid.trim()))==!1)return;let h=n.tvprogram_highlightcolor||"yellow";this.olddata[t]||(this.olddata[t]=n),(!this.measures[t]||JSON.stringify(this.olddata[t])!=JSON.stringify(n))&&(this.measures[t]={origwidthItem:parseInt(n.tvprogram_widthItem)||120,timeItem:30,heightRow:parseInt(n.tvprogram_heightRow)||35,scrollbarWidth:this.getScrollbarWidth(),markerpositionpercent:n.tvprogram_markerpositionpercent/100||.25,dialogwidthpercent:n.tvprogram_dialogwidthpercent/100||.9,dialogheightpercent:n.tvprogram_dialogheightpercent/100||.9,showpictures:n.tvprogram_showpictures||!1}),$("#"+t+"broadcastdlg").data({dialogwidthpercent:this.measures[t].dialogwidthpercent,dialogheightpercent:this.measures[t].dialogheightpercent}),this.measures[t].widthItem||(this.measures[t].widthItem=this.measures[t].origwidthItem),((this.today||{})[t]||{}).prevday||$("#"+t+" .tv-container").html("Datapoints loading..."),this.visTvprogram.loadCategories(c,t,()=>this.createWidget(t,o,n,r)),this.visTvprogram.loadChannels(c,t,()=>this.createWidget(t,o,n,r)),this.visTvprogram.loadGenres(c,t,()=>this.createWidget(t,o,n,r));function d(S){return!S||Object.keys(S)==0}this.today[t]||(this.today[t]={today:new Date,prevday:null}),this.scroll[t]||(this.scroll[t]={time:new Date(0),position:0,marker:0,timeout:null,automatic:0});let v=this.visTvprogram.calcDate(this.today[t].today),m=this.visTvprogram.getDate(v,0);this.viewday[t]||(this.viewday[t]={viewday:m,prevday:null}),this.viewday[t].viewday=m;let g=this.visTvprogram.getDate(v,0);if(d(this.tvprogram[m])&&this.visTvprogram.loadProgram(c,t,m,(S,T)=>{if(T!="error"&&T!="nodata"){this.createWidget(t,o,n,r);return}else{if(this.today[t].prevday==null)return;this.today[t].today=new Date(this.today[t].prevday),this.viewday[t].viewday=new Date(this.viewday[t].prevday),this.createWidget(t,o,n,r);return}}),this.visTvprogram.categories.length==0||this.visTvprogram.categories[0]==="request"||this.visTvprogram.channels.length==0||this.visTvprogram.channels[0]==="request"||this.visTvprogram.genres.length==0||this.visTvprogram.genres[0]==="request"||d(this.visTvprogram.tvprogram[m]))return;this.viewday[t].viewday!=this.viewday[t].prevday&&(this.viewday[t].prevday=this.viewday[t].viewday),this.bound[a]||(this.bound[a]={}),this.bound[a][t]||(this.bound[a][t]=!1),a&&!this.bound[a][t]&&(this.bound[a][t]=!0,vis.binds.tvprogram.bindStates(l,[a+".config",a+".cmd",a+".favorites",a+".channelfilter",a+".show"],this.onChange.bind(this,t,o,n,r,c))),this.onclickChannelSave.name=="onclickChannelSave"&&(this.onclickChannelSave=this.onclickChannelSave.bind(this));let x=this.visTvprogram.getConfigChannelfilter(a);x.length==0&&(x=this.visTvprogram.channels.reduce((S,T,M)=>(M<4&&S.push(T.id),S),[]));let f=this.measures[t].widthItem,u=this.measures[t].heightRow,y=this.measures[t].heightRow,s=this.visTvprogram.realBackgroundColor($("#"+t)[0]);this.visTvprogram.checkStyle("background-color",$("#"+t)[0].style.cssText)==""&&$("#"+t).css("background-color",s);let i=48*f+u,k=n.tvprogram_headerfontpercent||125,C=n.tvprogram_broadcastfontpercent||75,p=0,b=$("#"+t).height()-y,H=(x.length+1)*y;H<b?p=H:p=b-this.measures[t].scrollbarWidth;let e="";e+=`<style> 
`,e+="#"+t+` * {
`,e+=`   box-sizing: border-box; 
`,e+=`} 
`,e+="#"+t+` .tv-container {
`,e+=`   width: 100%; 
`,e+=`   height: 100%; 
`,e+=`   white-space:nowrap; 
`,e+=`   display:flex; 
`,e+=`   flex-direction: column; 
`,e+=`} 
`,e+="#"+t+` .navcontainer {
`,e+=`   width: 100%; 
`,e+=`} 
`,e+="#"+t+` .scrollcontainer {
`,e+=`   flex-grow: 1; 
`,e+=`   overflow:auto; 
`,e+=`   width:100%; 
`,e+=`} 
`,e+="#"+t+` .tv-row {
`,e+=`   margin: 0px; 
`,e+=`   padding: 0px; 
`,e+="   width: "+i+`px; 
`,e+=`} 
`,e+="#"+t+` .tv-item {
`,e+=`   display: inline-block; 
`,e+=`   vertical-align: middle; 
`,e+=`   border: solid #80808033; 
`,e+=`   border-width:1px 0px 0px 1px; 
`,e+=`} 
`,e+="#"+t+` .tv-head-time {
`,e+=`   position:sticky; 
`,e+=`   position: -webkit-sticky; 
`,e+=`   top:0px; 
`,e+=`   z-index:11; 
`,e+="   background-color: "+s+`; 
`,e+=`} 
`,e+="#"+t+` .tv-head-left {
`,e+=`   position:sticky; 
`,e+=`   position: -webkit-sticky; 
`,e+=`   left:0; 
`,e+=`   z-index:11; 
`,e+="   background-color: "+s+`; 
`,e+=`} 
`,e+="#"+t+` svg rect {
`,e+="   fill: "+$("#"+t).css("color")+`; 
`,e+=`} 
`,e+="#"+t+` .channel {
`,e+="   width: "+y+`px; 
`,e+="   height: "+y+`px; 
`,e+=`   padding: 1px; 
`,e+=`} 
`,e+="#"+t+` .time {
`,e+="   width: "+f+`px; 
`,e+="   height: "+y+`px; 
`,e+=`   font-weight: 700; 
`,e+="   font-size: "+k+`%; 
`,e+=`   padding: 5px 5px; 
`,e+=`} 
`,e+="#"+t+` .time:after {
`,e+=`   content:""; 
`,e+=`   display: inline-block; 
`,e+=`   vertical-align:middle; 
`,e+=`   height: 100%; 
`,e+=`} 
`,e+="#"+t+` .time span {
`,e+=`   vertical-align:middle; 
`,e+=`} 
`,e+="#"+t+` .broadcast {
`,e+="   height: "+y+`px; 
`,e+=`   padding: 3px; 
`,e+="   font-size: "+C+`%; 
`,e+=`   overflow: hidden; 
`,e+=`} 
`,e+="#"+t+` .broadcastelement {
`,e+=`   width: 100%; 
`,e+=`   height: 100%; 
`,e+=`   display: table-cell; 
`,e+=`} 
`,e+="#"+t+` .broadcastelement.hide {
`,e+=`   display: none; 
`,e+=`} 
`,e+="#"+t+` .broadcastelement .star  {
`,e+=`   display: inline-block; 
`,e+=`   margin: 0px 2px; 
`,e+=`} 
`,e+="#"+t+` .broadcastelement .star svg {
`,e+=`   height: 1em; 
`,e+=`   width: 1em; 
`,e+=`   position: relative; 
`,e+=`   top: .125em; 
`,e+=`} 
`,e+="#"+t+`broadcastdlg .star.selected svg  {
`,e+=`   filter: drop-shadow( 2px 2px 2px rgba(0, 0, 0, .7))
`,e+=`} 
`,e+="#"+t+" .broadcastelement.selected .star svg path, #"+t+`broadcastdlg .star.selected {
`,e+="   color: "+h+`; 
`,e+=`} 
`,e+="#"+t+` .broadcastelement.selected {
`,e+="   color: "+h+`; 
`,e+="   background-color: "+this.visTvprogram.colorToRGBA(h,".1")+`; 
`,e+=`} 
`,e+="#"+t+` .broadcastimage {
`,e+="   height: "+(y-7)+`px; 
`,e+=`   padding-right: 3px; 
`,e+=`   float: left; 
`,e+=`} 
`,e+="#"+t+` .button {
`,e+=`   display:inline-block; 
`,e+="   width: "+y+`px; 
`,e+="   height: "+y+`px; 
`,e+="   background-color: "+s+`; 
`,e+=`   vertical-align: middle; 
`,e+=`   padding: 5px 5px; 
`,e+=`} 
`,e+="#"+t+` .dateinfo {
`,e+="   height: "+y+`px; 
`,e+=`   padding: 5px 5px; 
`,e+=`   position: absolute; 
`,e+=`   right: 0px; 
`,e+=`   border: 0px; 
`,e+=`} 
`,e+="#"+t+` .dateinfo:after {
`,e+=`   content:""; 
`,e+=`   display: inline-block; 
`,e+=`   vertical-align:middle; 
`,e+=`   height: 100%; 
`,e+=`} 
`,e+="#"+t+` .dateinfo span {
`,e+=`   vertical-align:middle; 
`,e+=`} 
`,e+=".ui-dialog."+t+` {
`,e+=`   z-index:12; 
`,e+=`} 
`,e+=`.clearfix {
`,e+=`   clear:both; 
`,e+=`   content:""; 
`,e+=`   display:table; 
`,e+=`} 
`,e+="#"+t+`channeldlg .chselect-container {
`,e+=`} 
`,e+="#"+t+`channeldlg ul.channel {
`,e+=`   margin:0px; 
`,e+=`   padding:0px; 
`,e+=`} 
`,e+="#"+t+`channeldlg .listitem  {
`,e+=`   float: left; 
`,e+=`} 
`,e+="#"+t+`channeldlg .listitem .channel {
`,e+=`   list-style: none; 
`,e+=`} 
`,e+="#"+t+`channeldlg .items  {
`,e+=`   list-style: none; 
`,e+=`   margin:0px; 
`,e+=`   padding:0px; 
`,e+=`} 
`,e+="#"+t+`channeldlg .channel {
`,e+=`   margin:5px; 
`,e+="   width: "+y*1.5+`px; 
`,e+="   height: "+y*1.5+`px; 
`,e+=`   list-style: none; 
`,e+=`} 
`,e+="#"+t+`channeldlg .items .channel[selected] {
`,e+=`   background-color:lightgray; 
`,e+=`} 
`,e+="."+t+`.no-titlebar .ui-dialog-titlebar {
`,e+=`   display:none; 
`,e+=`} 
`,e+="#"+t+`broadcastdlg  {
`,e+=`   z-index:12; 
`,e+=`} 
`,e+="#"+t+`broadcastdlg .event-container.tv-dlg-row {
`,e+=`   height:100%; 
`,e+=`   display:flex; 
`,e+=`   flex-direction:row; 
`,e+=`   overflow:hidden; 
`,e+=`} 
`,e+="#"+t+`broadcastdlg .event-container.tv-dlg-col {
`,e+=`   height:100%; 
`,e+=`   display:flex; 
`,e+=`   flex-direction:column; 
`,e+=`   overflow:hidden; 
`,e+=`   font-size:75%; 
`,e+=`} 
`,e+="#"+t+`broadcastdlg .event-picture.tv-dlg-row {
`,e+=`   width:50%; 
`,e+=`} 
`,e+="#"+t+`broadcastdlg .event-picture.tv-dlg-col {
`,e+=`   height:30%; 
`,e+=`} 
`,e+="#"+t+`broadcastdlg .event-data {
`,e+=`   overflow-y:auto; 
`,e+=`} 
`,e+="#"+t+`broadcastdlg .event-picture img {
`,e+=`   width:auto; 
`,e+=`   height:auto; 
`,e+=`   max-width:100%; 
`,e+=`   max-height:100%; 
`,e+=`   display:block; 
`,e+=`   margin:auto; 
`,e+=`} 
`,e+="#"+t+`broadcastdlg .event-picture img {
`,e+=`   width:auto; 
`,e+=`   height:auto; 
`,e+=`   max-width:100%; 
`,e+=`   max-height:100%; 
`,e+=`   display:block; 
`,e+=`   margin:auto; 
`,e+=`} 
`,e+="#"+t+`broadcastdlg .dialogcolumn.tv-dlg-row {
`,e+=`   flex:1; 
`,e+=`   padding:5px; 
`,e+=`} 
`,e+="#"+t+`broadcastdlg .dialogcolumn.tv-dlg-col {
`,e+=`   padding:5px; 
`,e+=`} 
`,e+="#"+t+`broadcastdlg .button {
`,e+=`   display:inline-block; 
`,e+=`   width: 35px; 
`,e+=`   height: 35px; 
`,e+=`   vertical-align: middle; 
`,e+=`   position: relative; 
`,e+=`   float: right; 
`,e+=`} 
`,e+="#"+t+` .tooltip {
`,e+=`   position: relative; 
`,e+=`} 
`,e+="#"+t+` .tooltip span[role=tooltip] {
`,e+=`   display: none; 
`,e+=`} 
`,e+="#"+t+` .tooltip:hover span[role=tooltip] {
`,e+=`   display: block; 
`,e+=`   position: absolute; 
`,e+=`   left: 3em; 
`,e+=`   border: 1px solid; 
`,e+=`   font-size: 75%; 
`,e+=`   padding: 0.2em; 
`,e+=`   z-index: 100; 
`,e+="   background-color: "+s+`; 
`,e+=`} 
`,e+="#"+t+" .scrollcontainer ul.tv-row:nth-child(odd)> li.broadcast:nth-child(odd),#"+t+` ul.tv-row:nth-child(odd)> li.time:nth-child(odd) {
`,e+=`   background-color: rgba(128, 128, 128, 0.65); 
`,e+=`} 
`,e+="#"+t+" .scrollcontainer ul.tv-row:nth-child(odd)> li.broadcast:nth-child(even),#"+t+` ul.tv-row:nth-child(odd)> li.time:nth-child(even) {
`,e+=`   background-color: rgba(128, 128, 128, 0.55); 
`,e+=`} 
`,e+="#"+t+` .scrollcontainer ul.tv-row:nth-child(even)> li.broadcast:nth-child(odd) {
`,e+=`   background-color: rgba(128, 128, 128, 0.45); 
`,e+=`} 
`,e+="#"+t+` .scrollcontainer ul.tv-row:nth-child(even)> li.broadcast:nth-child(even) {
`,e+=`   background-color: rgba(128, 128, 128, 0.35); 
`,e+=`} 
`,e+="#"+t+` .line {
`,e+=`   position: absolute; 
`,e+=`   top: 0; 
`,e+=`   width: 2px; 
`,e+=`   background-color: red; 
`,e+=`   opacity: 0.8; 
`,e+=`   z-index: 10; 
`,e+="   height: "+p+`px; 
`,e+=`   float: left; 
`,e+=`} 
`,e+="#"+t+` .disable-select {
`,e+=`   -webkit-user-select: none; 
`,e+=`   -moz-user-select: none; 
`,e+=`   -ms-user-select: none; 
`,e+=`   -user-select: none; 
`,e+=`} 
`,e+="#"+t+` .staricon {
`,e+=`     background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100%' height='100%' viewBox='0 0 24 24'><path fill='currentColor' d='M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z' /></svg>"); 
`,e+=`} 
`,e+=`</style> 
`,e+='  <div class="svgcontainer">',e+='<svg style="display:none;"><symbol id="star-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="check-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"></path></symbol></svg>',e+='<svg style="display:none;"><symbol id="cancel-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"></path></symbol></svg>',e+='<svg style="display:none;"><symbol id="copy-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M19,21H8V7H19M19,5H8A2,2 0 0,0 6,7V21A2,2 0 0,0 8,23H19A2,2 0 0,0 21,21V7A2,2 0 0,0 19,5M16,1H4A2,2 0 0,0 2,3V17H4V3H16V1Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="switch-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M21,3H3C1.89,3 1,3.89 1,5V17A2,2 0 0,0 3,19H8V21H16V19H21A2,2 0 0,0 23,17V5C23,3.89 22.1,3 21,3M21,17H3V5H21M16,11L9,15V7" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="burger-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M3,6H21V8H3V6M3,11H21V13H3V11M3,16H21V18H3V16Z"></path></symbol></svg>',e+='<svg style="display:none;"><symbol id="nav-prevD-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M20,9V15H12V19.84L4.16,12L12,4.16V9H20Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="nav-center-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4M12,9A3,3 0 0,0 9,12A3,3 0 0,0 12,15A3,3 0 0,0 15,12A3,3 0 0,0 12,9Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="nav-nextD-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M4,15V9H12V4.16L19.84,12L12,19.84V15H4Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="zoom-minus-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M15.5,14H14.71L14.43,13.73C15.41,12.59 16,11.11 16,9.5A6.5,6.5 0 0,0 9.5,3A6.5,6.5 0 0,0 3,9.5A6.5,6.5 0 0,0 9.5,16C11.11,16 12.59,15.41 13.73,14.43L14,14.71V15.5L19,20.5L20.5,19L15.5,14M9.5,14C7,14 5,12 5,9.5C5,7 7,5 9.5,5C12,5 14,7 14,9.5C14,12 12,14 9.5,14M7,9H12V10H7V9Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="zoom-center-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12,9A3,3 0 0,0 9,12A3,3 0 0,0 12,15A3,3 0 0,0 15,12A3,3 0 0,0 12,9M19,19H15V21H19A2,2 0 0,0 21,19V15H19M19,3H15V5H19V9H21V5A2,2 0 0,0 19,3M5,5H9V3H5A2,2 0 0,0 3,5V9H5M5,15H3V19A2,2 0 0,0 5,21H9V19H5V15Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="zoom-plus-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M15.5,14L20.5,19L19,20.5L14,15.5V14.71L13.73,14.43C12.59,15.41 11.11,16 9.5,16A6.5,6.5 0 0,1 3,9.5A6.5,6.5 0 0,1 9.5,3A6.5,6.5 0 0,1 16,9.5C16,11.11 15.41,12.59 14.43,13.73L14.71,14H15.5M9.5,14C12,14 14,12 14,9.5C14,7 12,5 9.5,5C7,5 5,7 5,9.5C5,12 7,14 9.5,14M12,10H10V12H9V10H7V9H9V7H10V9H12V10Z" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="record-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M12.5,5A7.5,7.5 0 0,0 5,12.5A7.5,7.5 0 0,0 12.5,20A7.5,7.5 0 0,0 20,12.5A7.5,7.5 0 0,0 12.5,5M7,10H9A1,1 0 0,1 10,11V12C10,12.5 9.62,12.9 9.14,12.97L10.31,15H9.15L8,13V15H7M12,10H14V11H12V12H14V13H12V14H14V15H12A1,1 0 0,1 11,14V11A1,1 0 0,1 12,10M16,10H18V11H16V14H18V15H16A1,1 0 0,1 15,14V11A1,1 0 0,1 16,10M8,11V12H9V11" /></symbol></svg>',e+='<svg style="display:none;"><symbol id="hide-icon" viewBox="0 0 24 24"><path fill="currentColor" d="M2,5.27L3.28,4L20,20.72L18.73,22L15.65,18.92C14.5,19.3 13.28,19.5 12,19.5C7,19.5 2.73,16.39 1,12C1.69,10.24 2.79,8.69 4.19,7.46L2,5.27M12,9A3,3 0 0,1 15,12C15,12.35 14.94,12.69 14.83,13L11,9.17C11.31,9.06 11.65,9 12,9M12,4.5C17,4.5 21.27,7.61 23,12C22.18,14.08 20.79,15.88 19,17.19L17.58,15.76C18.94,14.82 20.06,13.54 20.82,12C19.17,8.64 15.76,6.5 12,6.5C10.91,6.5 9.84,6.68 8.84,7L7.3,5.47C8.74,4.85 10.33,4.5 12,4.5M3.18,12C4.83,15.36 8.24,17.5 12,17.5C12.69,17.5 13.37,17.43 14,17.29L11.72,15C10.29,14.85 9.15,13.71 9,12.28L5.6,8.87C4.61,9.72 3.78,10.78 3.18,12Z" /></symbol></svg>',e+="  </div>",e+='  <div class="navcontainer">',e+='    <ul class="tv-row tv-head-top">',e+=this.getButtonHeader(m).join(""),e+="    </ul>",e+="  </div>",e+='  <div class="scrollcontainer">',e+='    <ul class="tv-row tv-head-time">',e+='      <div class="line"></div>',e+='      <li class="tv-item tv-head-left channel">',e+="      </li>",e+=this.getTimetable().join(""),e+="    </ul>",this.getEvents(this.visTvprogram.tvprogram[g],x).map(S=>{e+='    <ul class="tv-row">',e+=this.getBroadcasts4Channel(S,t,o,g,a,c).join(""),e+="    </ul>"}),$("#"+t+" .tv-container").html(e),this.visTvprogram.getConfigShow(a)==1?$("#"+t+' .broadcastelement:not(".selected") > *').show():$("#"+t+' .broadcastelement:not(".selected") > *').hide(),console.log("Display day:"+m),$("#"+t+" .burger").click(function(S,T,M,B){vis.binds.tvprogram.time1.onclickChannel(S,M,T,B)}.bind(this,t,a,c)),$("#"+t+" .button.nav.prevD").off("click.onClickDay").on("click.onClickDay",this.onClickDay.bind(this,t,o,n,r)),$("#"+t+" .button.nav.nextD").off("click.onClickDay").on("click.onClickDay",this.onClickDay.bind(this,t,o,n,r)),$("#"+t+" .button.nav.center").off("click.onClickDay").on("click.onClickDay",this.onClickDay.bind(this,t,o,n,r)),$("#"+t+" .button.zoom.minus").off("click.onClickZoom").on("click.onClickZoom",this.onClickZoom.bind(this,t,o,n,r)),$("#"+t+" .button.zoom.plus").off("click.onClickZoom").on("click.onClickZoom",this.onClickZoom.bind(this,t,o,n,r)),$("#"+t+" .button.zoom.center").off("click.onClickZoom").on("click.onClickZoom",this.onClickZoom.bind(this,t,o,n,r)),$("#"+t+" .button.hide").off("click.onClickHide").on("click.onClickHide",this.onClickHide.bind(this,c,a,t)),$("#"+t+" .scrollcontainer").scroll(function(S){this.scroll[S].automatic==0&&(this.scroll[S].automatic=2),this.scroll[S].time=new Date,this.calcScroll(S)}.bind(this,t)),this.visTvprogram.copyStyles("font",$("#"+t).get(0),$("#"+t+"broadcastdlg").get(0)),this.visTvprogram.copyStyles("color",$("#"+t).get(0),$("#"+t+"broadcastdlg").get(0)),this.visTvprogram.copyStyles("background-color",$("#"+t).get(0),$("#"+t+"broadcastdlg").get(0)),this.updateMarker(t,this.today[t].today),this.timer[t]?(clearInterval(this.timer[t]),this.timer[t]=setInterval(this.updateMarker.bind(this,t,this.today[t].today),15e3)):this.timer[t]=setInterval(this.updateMarker.bind(this,t,this.today[t].today),15e3),this.scroll[t].position==0?(this.calcScroll(t),this.setScroll(t)):this.setScroll(t)},onClickHide:function(t,o){this.visTvprogram.toggleShow(t,o)},onClickZoom:function(t,o,n,r,l){console.log("ClickZoom:"+$(l.currentTarget).attr("class")),$(l.currentTarget).hasClass("plus")&&(this.measures[t].widthItem=this.measures[t].widthItem+this.measures[t].origwidthItem/4),$(l.currentTarget).hasClass("minus")&&(this.measures[t].widthItem=this.measures[t].widthItem-this.measures[t].origwidthItem/4),$(l.currentTarget).hasClass("center")&&(this.measures[t].widthItem=this.measures[t].origwidthItem),this.measures[t].widthItem<20&&(this.measures[t].widthItem=this.measures[t].origwidthItem),this.calcScroll(t),this.createWidget(t,o,n,r)},onClickDay:function(t,o,n,r,l){console.log("ClickNav:"+$(l.currentTarget).attr("class"));let a=0;$(l.currentTarget).hasClass("prevD")&&(a=-1),$(l.currentTarget).hasClass("nextD")&&(a=1),$(l.currentTarget).hasClass("center")?(this.today[t].today=new Date,this.scroll[t].position=0):(this.today[t].prevday=new Date(this.today[t].today),this.today[t].today=new Date(this.today[t].today.setDate(this.today[t].today.getDate()+a))),this.scroll[t].time=new Date(0),this.createWidget(t,o,n,r)},calcScroll:function(t){let o=$("#"+t+" .scrollcontainer").get(0);o&&(o.scrollLeft==0||this.scroll[t].position==0?this.scroll[t].position=this.scroll[t].marker/o.scrollWidth:this.scroll[t].position=(o.scrollLeft+o.clientWidth*this.measures[t].markerpositionpercent)/o.scrollWidth)},setScroll:function(t){try{let o=$("#"+t+" .scrollcontainer").get(0);if(!o.scrollWidth)return;o.scrollLeft=this.scroll[t].position*o.scrollWidth-o.clientWidth*this.measures[t].markerpositionpercent}catch(o){console.log(o)}},updateMarker:function(t,o){if(this.scroll[t].automatic==2&&new Date-this.scroll[t].time<90*1e3)return;this.scroll[t].automatic=0,this.visTvprogram.calcDate(o).toLocaleDateString()!=this.visTvprogram.calcDate(new Date).toLocaleDateString()?$("#"+t+" .line").hide():$("#"+t+" .line").show();let n=this.measures[t].widthItem,r=this.measures[t].timeItem,l=this.measures[t].heightRow,a=new Date(this.visTvprogram.calcDate(new Date));a.setHours(5),a.setMinutes(0),a.setSeconds(0);let c=new Date(a);c.setDate(c.getDate()+1);let d=l+Math.floor((new Date-a)/6e4/r*n*10)/10;$("#"+t+" .line").css("left",d+"px"),this.scroll[t].marker=d,this.scroll[t].position=0,this.calcScroll(t),this.scroll[t].timeout&&clearTimeout(this.scroll[t].timeout),this.scroll[t].automatic=1,this.scroll[t].timeout=window.setTimeout(function(){this.scroll[t].automatic=0,clearTimeout(this.scroll[t].timeout),this.scroll[t].timeout=null}.bind(this),500),this.setScroll(t)},getScrollbarWidth:function(){let t=document.createElement("div");t.className="scrollbar-measure",t.style.cssText="width: 100px;height: 100px;overflow: scroll;position: absolute;top: -9999px;",document.body.appendChild(t);let o=t.offsetWidth-t.clientWidth;return document.body.removeChild(t),o},getChannels:function(t,o=[]){let n=[];return o.map(r=>{let l=t.find(a=>a.id==r);n.push('<li class="listitem channel" data-order="'+l.order+'" data-id="'+l.id+'" selected><img width="100%" height="100%" src="https://tvfueralle.de/channel-logos/'+l.channelId+'.png" alt="" class="channel-logo"></li>')}),t.sort((r,l)=>r.order+(o.indexOf(r.id)==-1)*1e5-(l.order+(o.indexOf(l.id)==-1)*1e5)).map(r=>{o.findIndex(l=>l==r.id)==-1&&n.push('<li class="listitem channel" data-order="'+r.order+'" data-id="'+r.id+'"><img width="100%" height="100%" src="https://tvfueralle.de/channel-logos/'+r.channelId+'.png" alt="" class="channel-logo"></li>')}),n},onclickChannelSave:function(t,o){let n=t.dataset.widgetid;if(o){let r=t.dataset.dp||"",l=t.dataset.instance||"";this.visTvprogram.setConfigChannelfilter(l,r,$("#"+n+"channeldlg .chselect-container .channel[selected]").toArray().map(a=>parseInt(a.dataset.id)))}$("#"+n+"channeldlg").dialog("close")},onclickChannel:function(t,o,n){let r=!1,l=this.visTvprogram.channels,a=this.visTvprogram.getConfigChannelfilter(n);a.length==0&&(a=l.reduce((h,d,v)=>(v<4&&h.push(d.id),h),[]));let c="";c+='  <div class="chselect-container clearfix">',c+='    <ul class="listitem channel" data-instance="'+o+'" data-dp="'+n+'" data-widgetid="'+t+'" onclick="vis.binds.tvprogram.time1.onclickChannelSave(this,true)" ><li class="channel"><svg width="100%" height="100%" ><use xlink:href="#check-icon"></use></svg></li></ul>',c+='    <ul class="listitem channel" data-widgetid="'+t+'" onclick="vis.binds.tvprogram.time1.onclickChannelSave(this,false)"><li class="channel"><svg width="100%" height="100%" ><use xlink:href="#cancel-icon"></use></svg></li></ul>',c+="  </div>",c+='  <div class="chselect-container clearfix sortable">',c+='  <ul class="items">',c+=this.getChannels(l,a).join(`
`),c+="  </ul>",c+="  </div>",$("#"+t+"channeldlg").html(c),$(".chselect-container .items .channel").click(function(){if(console.log("channel click"),r)return;let h=$(this).parent().find("[selected]").last();this.dataset.id&&($(this).attr("selected")?$(this).removeAttr("selected"):$(this).attr("selected","")),$(this).attr("selected")?$(this).insertAfter(h):$(this).parent().children().sort(function(d,v){return d.dataset.order+($(d).attr("selected")!="selected")*1e5-(v.dataset.order+($(v).attr("selected")!="selected")*1e5)}).appendTo($(this).parent())}),$(".chselect-container.sortable").sortable({items:".items .channel[selected]",containment:"parent",revert:!0,grid:[5,5],opacity:.8,tolerance:"pointer",start:function(){r=!0},stop:function(){r=!1}}),$("#"+t+"channeldlg").dialog({resizable:!1,autoOpen:!1,modal:!1,position:{of:$("#"+t)},width:$("#"+t).width()*this.measures[t].dialogwidthpercent,height:$("#"+t).height()*this.measures[t].dialogheightpercent,dialogClass:"no-titlebar "+t,zIndex:10003,stack:!1}),this.visTvprogram.copyStyles("font",$("#"+t).get(0),$("#"+t+"channeldlg").get(0)),this.visTvprogram.copyStyles("color",$("#"+t).get(0),$("#"+t+"channeldlg").get(0)),this.visTvprogram.copyStyles("background-color",$("#"+t).get(0),$("#"+t+"channeldlg").get(0)),$("#"+t+"channeldlg").dialog("open")},getBroadcasts4Channel:function(t,o,n,r,l,a){let c=this.measures[o].widthItem,h=this.measures[o].timeItem,d=this.visTvprogram.getConfigFavorites(l),v,m=new Date(t.events[0].airDate);m.setHours(5),m.setMinutes(0);let g=new Date(m);g.setDate(g.getDate()+1);let x=this.visTvprogram.channels.find(i=>i.id==t.channel),f=[],u="";u+='    <li class="tv-item tv-head-left channel">',u+='      <img width="100%" height="100%" data-instance="'+a+'" data-channelid="'+x.channelId+'" data-dp="'+l+'" src="https://tvfueralle.de/channel-logos/'+x.channelId+'.png" alt="" class="channel-logo"  onclick="vis.binds.tvprogram.onclickChannelSwitch(this,event)">',u+="    </li>",f.push(u);for(let i=0;i<t.events.length;i++){let k=t.events[i],C=new Date(k.startTime),p=new Date(k.endTime);C>=g||p<=m||(i==0&&C>m&&f.push('<li class="tv-item broadcast" style="left:0px; width:'+Math.floor((C-m)/6e4/h*c*10)/10+'px;"></li>'),C<m&&(C=m),p>g&&(p=g),v=d.indexOf(k.title)>-1,u="",u+='<li class="tv-item broadcast" style="',u+="left:"+Math.floor((C-m)/6e4/h*c*10)/10+"px;",u+="width:"+Math.floor((p-C)/6e4/h*c*10)/10+'px;">',u+='<div class="broadcastelement '+(v?"selected":"")+'" data-widgetid="'+o+'" data-eventid="'+k.id+'" data-viewdate="'+r+'" data-instance="'+a+'" data-dp="'+l+'" data-view="'+n+'" onclick="vis.binds.tvprogram.onclickBroadcast(this)">',k.photo.url&&this.measures[o].showpictures&&(u+='<div><img class="broadcastimage" src="https://tvfueralle.de'+k.photo.url+'"></div>'),u+='<div class="broadcasttitle">'+k.title,u+='<div class="star" data-viewdate="'+r+'" data-eventid="'+k.id+'" data-dp="'+l+'" data-instance="'+a+'" onclick="return vis.binds.tvprogram.onclickFavorite(this,event)"><svg width="100%" height="100%" ><use xlink:href="#star-icon"></use></svg></div>',u+="</div>",u+='<div class="broadcasttime">',u+=("0"+C.getHours()).slice(-2)+":"+("0"+C.getMinutes()).slice(-2),u+=" - ",u+=("0"+p.getHours()).slice(-2)+":"+("0"+p.getMinutes()).slice(-2),u+="</div></div></li>",f.push(u))}let y=new Date(t.events[t.events.length-1].startTime),s=new Date(t.events[t.events.length-1].endTime);return y<g&&s<g&&(y=s,s=g,u="",u+='<li class="tv-item broadcast" style="',u+="left:"+Math.floor((y-m)/6e4/h*c*10)/10+"px;",u+="width:"+Math.floor((s-y)/6e4/h*c*10)/10+'px;">',u+="</li>",f.push(u)),f},getEvents:function(t,o){let n=[],r;return t.map(l=>{(r=o.indexOf(l.channel))>-1&&(n[r]||(n[r]={}),n[r].events||(n[r].events=[]),n[r].channel=l.channel,n[r].events.push(l))}),n},getTimetable:function(){let t=[];for(let o=0;o<24;o++)t.push('<li class="tv-item time"><span>'+("0"+o).slice(-2)+":00</span></li>"),t.push('<li class="tv-item time"><span>'+("0"+o).slice(-2)+":30</span></li>");return[].concat(t.slice(10),t.slice(0,10))},getButtonHeader:function(t){let o=[];return o.push('<li class="tv-item tv-head-topleft tv-head-left button burger tooltip"><span role="tooltip">Menu</span><svg width="100%" height="100%" ><use xlink:href="#burger-icon"></use></svg></li>'),o.push('<li class="tv-item button nav prevD tooltip"><span role="tooltip">Previous day</span><svg width="100%" height="100%" ><use xlink:href="#nav-prevD-icon"></use></svg></li>'),o.push('<li class="tv-item button nav center tooltip"><span role="tooltip">Today</span><svg width="100%" height="100%" ><use xlink:href="#nav-center-icon"></use></svg></li>'),o.push('<li class="tv-item button nav nextD tooltip"><span role="tooltip">Next day</span><svg width="100%" height="100%" ><use xlink:href="#nav-nextD-icon"></use></svg></li>'),o.push('<li class="tv-item button zoom minus tooltip"><span role="tooltip">Zoom in</span><svg width="100%" height="100%" ><use xlink:href="#zoom-minus-icon"></use></svg></li>'),o.push('<li class="tv-item button zoom center tooltip"><span role="tooltip">Zoom normal</span><svg width="100%" height="100%" ><use xlink:href="#zoom-center-icon"></use></svg></li>'),o.push('<li class="tv-item button zoom plus tooltip"><span role="tooltip">Zoom out</span><svg width="100%" height="100%" ><use xlink:href="#zoom-plus-icon"></use></svg></li>'),o.push('<li class="tv-item button hide tooltip"><span role="tooltip">Hide Non-Favorites</span><svg width="100%" height="100%" ><use xlink:href="#hide-icon"></use></svg></li>'),o.push('<li class="tv-item dateinfo">'+new Date(t).toLocaleDateString(navigator.language,{weekday:"short"})+", "+new Date(t).toLocaleDateString()+"</li>"),o},onChange:function(t,o,n,r,l,a,c){let h=a.type.split(".");if((h[3]=="config"||h[3]=="favorites"||h[3]=="channelfilter"||h[3]=="show")&&h[4]=="val"&&(console.log("changed "+t+" type:"+a.type+" val:"+c),this.createWidget(t,o,n,r)),h[3]=="cmd"&&h[4]=="val"&&c&&c!=""){console.log("changed "+t+" type:"+a.type+" val:"+c);let d=c.split("|");d[0]=="new"&&(d[1]!="program"&&this.visTvprogram.getServerData(l,t,d[1],function(v,m,g,x,f){this[d[1]]=f,this.createWidget(v,m,g,x)}.bind(this,t,o,n,r)),d[1]=="program"&&this.tvprogram[d[2]]&&this.visTvprogram.loadProgram(l,t,d[2],function(v,m,g,x,f,u){if(u!="error"&&u!="nodata"){this.tvprogram[f]=u,this.createWidget(v,m,g,x);return}}.bind(this,t,o,n,r,d[2])))}}},checkStyle:function(t,o){return o.split(";").reduce((n,r)=>r.split(":")[0].trim()==t?r.split(":")[1].trim():n,"")},realBackgroundColor:function(t){let o="rgba(0, 0, 0, 0)",n="transparent";if(!t)return o;let r=getComputedStyle(t).backgroundColor;return r===o||r===n?this.realBackgroundColor(t.parentElement):r},onclickBroadcast:function(t){let o=t.currentTarget?t.currentTarget:t,n=o.dataset.eventid||0,r=o.dataset.widgetid||0,l=o.dataset.view||0,a=o.dataset.viewdate||0,c=o.dataset.instance||"",h=o.dataset.dp||"";n==0||r==0||this.getServerBroadcast(c,n,a,function(d,v,m){let g=m,x=$("#"+d+"broadcastdlg").data(),f=new Date(g.startTime),u=new Date(g.endTime),y=g.content.category?this.categories.find(M=>M.id==g.content.category):null,s=g.channel?this.channels.find(M=>M.id==g.channel):null,i="";i+=s?s.name+" ":"",i+=("0"+f.getHours()).slice(-2)+":"+("0"+f.getMinutes()).slice(-2),i+=" - ",i+=("0"+u.getHours()).slice(-2)+":"+("0"+u.getMinutes()).slice(-2);let k="";k+=g.content.country?g.content.country+" ":"",k+=g.content.year?g.content.year+" ":"",k+=y?y.title+" ":"";let C="",p="";g.content.seasonNumber&&(C=g.content.seasonNumber,C=C<100?"S"+("0"+C).slice(-2):"S"+C),g.content.episodeNumber&&(p=g.content.episodeNumber,p=p<100?"E"+("0"+p).slice(-2):"E"+p),k+=C||p?C+p+" ":"";let b=g.content.texts.Long.value?g.content.texts.Long.value:g.content.texts.VeryShort.value?g.content.texts.VeryShort.value:"",H=g.photo.url?"https://tvfueralle.de"+g.photo.url:"https://tvfueralle.de/tv-logo-no-image.svg",V=this.getConfigFavorites(h).indexOf(g.title)>-1,S=$("#"+d).width()*x.dialogwidthpercent>$("#"+d).height()*x.dialogheightpercent?" tv-dlg-row":" tv-dlg-col",T="";T+='  <div class="event-container'+S+'" data-eventid="'+g.id+'">',T+='    <div class="event-picture dialogcolumn'+S+'">',T+='    <img src="'+H+'">',T+="    </div>",T+='    <div class="event-data dialogcolumn'+S+'">',T+='      <div class="buttoncontainer">',T+='          <div class="record button" data-viewdate="'+a+'" data-eventid="'+g.id+'" data-instance="'+c+'" data-dp="'+h+'" onclick="return vis.binds.tvprogram.onclickRecord(this,event)"><svg width="100%" height="100%" ><use xlink:href="#record-icon"></use></svg></div>',T+='          <div class="copy button" data-widgetid="'+d+'" onclick="return vis.binds.tvprogram.onclickCopy(this,event)"><svg width="100%" height="100%" ><use xlink:href="#copy-icon"></use></svg></div>',T+='          <div class="star button '+(V?"selected":"")+'" data-viewdate="'+a+'" data-eventid="'+g.id+'" data-instance="'+c+'" data-dp="'+h+'" onclick="return vis.binds.tvprogram.onclickFavorite(this,event)"><svg width="100%" height="100%" ><use xlink:href="#star-icon"></use></svg></div>',f<new Date&&new Date<u&&(T+='        <div class="channelselect button" data-instance="'+c+'" data-dp="'+h+'" data-channelid="'+s.channelId+'" onclick="vis.binds.tvprogram.onclickChannelSwitch(this,event)"><svg width="100%" height="100%" ><use xlink:href="#switch-icon"></use></svg></div>'),T+="      </div>",T+='      <div style="padding: 0px 0px 5px;">'+i+"</div>",T+='      <div style="font-weight: bold;padding: 0px 0px 5px;">'+g.title+"</div>",T+='      <div style="padding: 0px 0px 5px;">'+k+"</div>",T+="      <div>"+b+"</div>",T+="    </div>",T+="  </div>",T+="  </div>",$("#"+d+"broadcastdlg").html(T),$("#"+d+"broadcastdlg").dialog({resizable:!1,autoOpen:!1,modal:!1,position:{of:$("#"+d),within:$("#"+d)},width:$("#"+d).width()*x.dialogwidthpercent,height:$("#"+d).height()*x.dialogheightpercent,dialogClass:"no-titlebar "+d,zIndex:10003,stack:!1,collision:"none"}),this.copyStyles("font",$("#"+d).get(0),$("#"+d+"broadcastdlg").get(0)),this.copyStyles("color",$("#"+d).get(0),$("#"+d+"broadcastdlg").get(0)),this.copyStyles("background-color",$("#"+d).get(0),$("#"+d+"broadcastdlg").get(0)),$("#"+d+"broadcastdlg").dialog("open"),$("#"+d+"broadcastdlg").click(function(){$("#"+d+"broadcastdlg").dialog("close")})}.bind(this,r,l))},onclickRecord:function(t,o){let n=t.dataset.instance||"",r=t.dataset.dp||"",l=t.dataset.eventid||0,a=t.dataset.viewdate||0;l==0||a==0||(this.getServerBroadcast(n,l,a,function(c,h){let d=h,v=d.channel?this.channels.find(g=>g.id==d.channel):null,m={startTime:d.startTime,endTime:d.endTime,title:d.title,channel:d.channel,channelid:v.channelId,channelname:v.name,eventid:d.id};this.setValueAck(n,r+".record",JSON.stringify(m))}.bind(this,t)),o.stopPropagation())},onclickCopy:function(t,o){let n=t.dataset.widgetid||"",r=document.createElement("textarea");r.value=$("#"+n+"broadcastdlg .event-data").get(0).outerText,document.body.appendChild(r),r.focus(),r.select(),document.execCommand("copy"),document.body.removeChild(r),o.stopPropagation()},copyStyles:function(t,o,n){let r=window.getComputedStyle(o),l=window.getComputedStyle(n);for(let a=r.length;a--;)r[a].startsWith(t)&&r.getPropertyValue(r[a])!=l.getPropertyValue(r[a])&&n.style.setProperty(r[a],r.getPropertyValue(r[a]))},colorToRGBA:function(t,o=1){let n=document.createElement("canvas");n.height=1,n.width=1;let r=n.getContext("2d");r.fillStyle=t,r.fillRect(0,0,1,1);let l=r.getImageData(0,0,1,1).data;return"rgba("+l[0]+","+l[1]+","+l[2]+","+o+")"},onclickChannelSwitch:function(t,o){let n=t.dataset.channelid||"",r=t.dataset.dp||"",l=t.dataset.instance||"";this.setValueAck(l,r+".selectchannel",n),o.stopPropagation()},onclickFavorite:function(t,o){let n=t.dataset.dp||"",r=t.dataset.instance||"",l=t.dataset.eventid||0,a=t.dataset.viewdate||0;l==0||a==0||(this.getServerBroadcast(r,l,a,function(c,h){let d=h,v=this.getConfigFavorites(n),m=v.indexOf(d.title);m>-1?(v.splice(m,1),$(c).hasClass("button")&&$(c).removeClass("selected")):(v.push(d.title),$(c).hasClass("button")&&$(c).addClass("selected")),this.setConfigFavorites(r,n,v)}.bind(this,t)),o.stopPropagation())},getConfig:function(t){let o,n=vis.states.attr(t+".config.val");return typeof n!="undefined"&&n!=="null"&&n!==""?o=JSON.parse(n):o={},o},getConfigFavorites:function(t){let o,n=vis.states.attr(t+".favorites.val");return typeof n!="undefined"&&n!=="null"&&n!==""?o=JSON.parse(n):o=[],o},setConfigFavorites:function(t,o,n){this.setValueAck(t,o+".favorites",JSON.stringify(n))},getConfigChannelfilter:function(t){let o,n=vis.states.attr(t+".channelfilter.val");return typeof n!="undefined"&&n!=="null"&&n!==""?o=JSON.parse(n):o=[],o},setConfigChannelfilter:function(t,o,n){this.setValueAck(t,o+".channelfilter",JSON.stringify(n))},getConfigShow:function(t){let o,n=vis.states.attr(t+".show.val");return typeof n!="undefined"&&n!=="null"&&n!==""?o=JSON.parse(n):o=1,o},setConfigShow:function(t,o,n){this.setValueAck(t,o+".show",JSON.stringify(n))},toggleShow:function(t,o){let n=this.getConfigShow(o);n==null&&(n=0),n=n==1?0:1,this.setConfigShow(t,o,n)},getServerBroadcast:function(t,o,n,r){console.log("getServerBroadcast request "+o+"."+n),vis.conn.sendTo(t,"getServerBroadcast",{eventid:o,viewdate:n},function(l){l!="error"&&l!="nodata"?console.log("getServerBroadcast received ok "+t+"."+n+"."+o):console.log("getServerBroadcast received "+l),r&&r(l)}.bind(this))},events:{},serverdata:{},getServerData:function(t,o,n,r){let l=this,a=t+n;Object.prototype.hasOwnProperty.call(l.serverdata,a)&&r(l.serverdata[a]),Object.prototype.hasOwnProperty.call(l.events,a)||(l.events[a]=[]);let c=l.events[a];c.find(h=>h.key==o)||c.push({key:o,cb:r}),vis.conn.sendTo(t,"getServerData",n,function(h){if(h!="error"&&h!="nodata"?console.log("getServerData received "+t+"."+n+" "+JSON.stringify(h).substring(0,100)):console.log("getServerData received err "+h),l.serverdata[a]=h,!Object.prototype.hasOwnProperty.call(l.events,a))return;let d=l.events[a];for(let v=0;v<d.length;v++)d[v].cb(h);delete l.events[a]})},getServerTVProgram:function(t,o,n,r){let l=t+"program."+n;if(Object.prototype.hasOwnProperty.call(this.serverdata,l)&&r(this.serverdata[l]),Object.prototype.hasOwnProperty.call(this.events,l)){this.events[l].find(a=>a.key==o)||this.events[l].push({key:o,cb:r});return}else this.events[l]=[{key:o,cb:r}];vis.conn.sendTo(t,"getServerTVProgram",n,function(a){if(a!="error"&&a!="nodata"?console.log("getServerTVProgram received "+t+"."+n+"nodata"):(console.log("getServerTVProgram received "+t+"."+n+" ok"),this.serverdata[l]=a),!!Object.prototype.hasOwnProperty.call(this.events,l)){for(let c=0;c<this.events[l].length;c++)this.events[l][c].cb(a);delete this.events[l]}}.bind(this))},getFavoritesData:function(t,o=[],n){console.log("getFavoritesData request "+t+".favorites"),vis.conn.sendTo(t,"getFavoritesDatax",o,r=>{r!="error"&&r!="nodata"?console.log("getFavoritesData received ok "+r.length):console.log("getFavoritesData received "+t+".favorites"),n&&n(r)})},getServerInfo:function(t,o){console.log("getServerInfo request "),vis.conn.sendTo(t,"getServerInfo",{},n=>{console.log("getFavoritesData received ok "),o&&o(n)})},getServerBroadcastNow:function(t,o,n){console.log("getServerBroadcastNow request "),vis.conn.sendTo(t,"getServerBroadcastNow",o,function(r){r!="error"&&r!="nodata"?console.log("getServerBroadcastNow received ok "+r.length):console.log("getServerBroadcastNow received "),n&&n(r)}.bind(this))},getServerBroadcastDate:function(t,o,n,r){console.log("getServerBroadcastDate request "),vis.conn.sendTo(t,"getServerBroadcastDate",{channelfilter:o,date:n},function(l){l!="error"&&l!="nodata"?console.log("getServerBroadcastDate received ok "+l.length):console.error("getServerBroadcastDate received "+l),r&&r(l)}.bind(this))},getServerBroadcastFind:function(t,o,n){console.log("getServerBroadcastFind request "),vis.conn.sendTo(t,"getServerBroadcastFind",o,function(r){r!="error"&&r!="nodata"?console.log("getServerBroadcastFind received ok "+r.length):console.log("getServerBroadcastFind received ");let l=[];r.map(a=>{a.events.map(c=>l.push(c))}),r=l.sort((a,c)=>new Date(a.startTime)-new Date(c.startTime)),n&&n(r)}.bind(this))},setValueAck:function(t,o,n){console.log("setValueAck request "),vis.conn.sendTo(t,"setValueAck",{id:o,value:n},function(){}.bind(this))},loadServerInfos:function(t,o,n=!1){this.infos!=null||n||(this.infos=[],this.getServerInfo(t,function(r){this.infos=r,o(r)}.bind(this)))},loadCategories:function(t,o,n,r=!1){this.categories!=null&&this.categories[0]!=="request"||r||(this.categories=["request"],this.getServerData(t,o,"categories",function(l){this.categories=l,n(l)}.bind(this)))},loadChannels:function(t,o,n,r=!1){this.channels!=null&&this.channels[0]!=="request"||r||(this.channels=["request"],this.getServerData(t,o,"channels",function(l){this.channels=l,n(l)}.bind(this)))},loadGenres:function(t,o,n,r=!1){this.genres!=null&&this.genres[0]!=="request"||r||(this.genres=["request"],this.getServerData(t,o,"genres",function(l){this.genres=l,n(l)}.bind(this)))},loadProgram:function(t,o,n,r,l=!1){this.tvprogram[n]||(this.tvprogram[n]=null),!(this.tvprogram[n]!=null||l)&&(this.tvprogram[n]=[],this.getServerTVProgram(t,o,n,function(a,c){c!="error"&&c!="nodata"&&(this.tvprogram[a]=c),r(a,c)}.bind(this,n)))},calcDate:function(t){let o=new Date(t),n=o.getHours()+o.getMinutes()/60;return n>=0&&n<5&&o.setDate(o.getDate()-1),o},getDate:function(t,o){let n=new Date(t);return n.setDate(n.getDate()+o),n.getFullYear()+"-"+("0"+(n.getMonth()+1)).slice(-2)+"-"+("0"+n.getDate()).slice(-2)},compareDate:function(t,o){return t.getDate()==o.getDate()&&t.getMonth()==o.getMonth()&&t.getYear()==o.getYear()},getTvprogramId:function(t){let o=t.split(".");return o.length<2?"":(o=o.slice(0,3),o.join("."))},getInstance:function(t){let o=t.split(".");return o.length<2?"":(o=o.slice(0,2),o.join("."))},bindStates:function(t,o,n){console.log("bindStates");let r=$(t),l=r.data("bound");if(l)for(let a=0;a<l.length;a++)vis.states.unbind(l[a],n);r.data("bound",null),r.data("bindHandler",null),vis.conn.gettingStates=0,vis.conn.getStates(o,function(a,c){vis.conn.subscribe(o);for(let h=0;h<o.length;h++)o[h]=o[h]+".val",vis.states.bind(o[h],n);vis.binds.tvprogram.updateStates(c),r.data("bound",o),r.data("bindHandler",n)}.bind({change_callback:n}))},updateStates:function(t){for(let o in t){if(!Object.prototype.hasOwnProperty.call(t,o))continue;let n=t[o];try{if(vis.editMode)vis.states[`${o}.val`]=n.val,vis.states[`${o}.ts`]=n.ts,vis.states[`${o}.ack`]=n.ack,vis.states[`${o}.lc`]=n.lc,n.q!==void 0&&n.q!==null&&(vis.states[`${o}.q`]=n.q);else{let r={};r[`${o}.val`]=n.val,r[`${o}.ts`]=n.ts,r[`${o}.ack`]=n.ack,r[`${o}.lc`]=n.lc,n.q!==void 0&&n.q!==null&&(r[`${o}.q`]=n.q),vis.states.attr(r)}}catch(r){console.error(`Error: can't create states object for ${o}(${r})`)}}}};vis.binds.tvprogram.showVersion();jQuery.fn.mydelay=function(t,o){return t=jQuery.fx&&jQuery.fx.speeds[t]||t,o=o||"fx",this.queue(o,function(n,r){let l=window.setTimeout(n,t);r.stop=function(){window.clearTimeout(l)}})}});_();})();
//# sourceMappingURL=tvprogram-dist.js.map
